# docker-compose.yml
# https://gis-ops.com/de/postgrest-tutorial-installation-and-setup/
 
services:

  postgrest:
    restart: always
    image: "postgrest/postgrest:v12.2.3"
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      VERSION: "1.0.1"
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/tfm"
      PGRST_DB_SCHEMA: public_api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      PGRST_DB_PRE_CONFIG: "basic_auth.pre_config"
      PGRST_OPENAPI_SECURITY_ACTIVE: "true"
      #PGRST_JWT_SECRET: "7u8f0HLDi5S6NKzNuo69cDEl3abvDP8YVfW3egLNubvy7uJFrP"
      #PGRST_JWT_SECRET_IS_BASE64: "false"
    
    depends_on:
      - postgres


  postgres:
    restart: always
    #name the container
    container_name: postgis
    image: "kartoza/postgis"
    command: -c logging_collector=on -c log_statement=all -c client_min_messages=notice

    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=tfm
      - SCHEMA_NAME=public_api
  
    volumes:

      # pgjwt & pgcrypto Extension
      - ./config/pgjwt/pgjwt.control:/usr/share/postgresql/13/extension/pgjwt.control
      - ./config/pgjwt/pgjwt--0.2.0-tfm.sql:/usr/share/postgresql/13/extension/pgjwt--0.2.0.sql
      

      ### Old Setup (deprecated)
      #- ./structure/structure.sql:/docker-entrypoint-initdb.d/20-structure.sql
      #- ./ci2027-db-data/data.sql:/docker-entrypoint-initdb.d/40-data.sql
      


      ### New Setup (to be implemented) 
      #- ./structure/ci2027/structure.sql:/docker-entrypoint-initdb.d/930-structure.sql
      - ./structure/ci2027/schema.sql:/docker-entrypoint-initdb.d/900-schema.sql
      - ./structure/ci2027/enum.sql:/docker-entrypoint-initdb.d/901-enum.sql
      - ./structure/ci2027/enum_overwrite.sql:/docker-entrypoint-initdb.d/902-enum_overwrite.sql
      - ./structure/ci2027/domains.sql:/docker-entrypoint-initdb.d/902-domains.sql
      
      

      ## Thünen intern data
      - ./config/10-pgcrypto.sql:/docker-entrypoint-initdb.d/904-pgcrypto.sql
      - ./config/11-postgrest-config.sql:/docker-entrypoint-initdb.d/905-postgrest-config.sql
      - ./structure/api.sql:/docker-entrypoint-initdb.d/906-api.sql

      

      ## SET DEFAULT GRANTS
      - ./structure/ci2027/grants.sql:/docker-entrypoint-initdb.d/907-grants.sql

      - ./ci2027-db-data/data.sql:/docker-entrypoint-initdb.d/908-data.sql

      

      #- ./structure/ci2027:/docker-entrypoint-initdb.d
      #- ci2027-db-structure/ci2027/lookup_tables:/docker-entrypoint-initdb.d
      - ./structure/ci2027/lookup_tables/lookup_growth_area.sql:/docker-entrypoint-initdb.d/910-lookup_growth_area.sql
      - ./structure/ci2027/lookup_tables/lookup_growth_district.sql:/docker-entrypoint-initdb.d/910-lookup_growth_district.sql
      - ./structure/ci2027/lookup_tables/lookup_state.sql:/docker-entrypoint-initdb.d/910-lookup_state.sql
      - ./structure/ci2027/lookup_tables/lookup_sampling_strata.sql:/docker-entrypoint-initdb.d/910-lookup_sampling_strata.sql
      - ./structure/ci2027/lookup_tables/lookup_layer_type.sql:/docker-entrypoint-initdb.d/910-lookup_layer_type.sql
      - ./structure/ci2027/lookup_tables/lookup_forest_decision.sql:/docker-entrypoint-initdb.d/910-lookup_forest_decision.sql
      - ./structure/ci2027/lookup_tables/lookup_property_type.sql:/docker-entrypoint-initdb.d/910-lookup_property_type.sql
      - ./structure/ci2027/lookup_tables/lookup_property_size_class.sql:/docker-entrypoint-initdb.d/910-lookup_property_size_class.sql
      - ./structure/ci2027/lookup_tables/lookup_height_layer_class.sql:/docker-entrypoint-initdb.d/910-lookup_height_layer_class.sql
      - ./structure/ci2027/lookup_tables/lookup_forestry_department.sql:/docker-entrypoint-initdb.d/910-lookup_forestry_department.sql
      - ./structure/ci2027/lookup_tables/lookup_forest_type.sql:/docker-entrypoint-initdb.d/910-lookup_forest_type.sql
      - ./structure/ci2027/lookup_tables/lookup_habitat_type.sql:/docker-entrypoint-initdb.d/910-lookup_habitat_type.sql
      - ./structure/ci2027/lookup_tables/lookup_habitat_type_source.sql:/docker-entrypoint-initdb.d/910-lookup_habitat_type_source.sql
      - ./structure/ci2027/lookup_tables/lookup_land_use.sql:/docker-entrypoint-initdb.d/910-lookup_land_use.sql
      - ./structure/ci2027/lookup_tables/lookup_use_restriction.sql:/docker-entrypoint-initdb.d/910-lookup_use_restriction.sql
      - ./structure/ci2027/lookup_tables/lookup_marking_state.sql:/docker-entrypoint-initdb.d/910-lookup_marking_state.sql
      - ./structure/ci2027/lookup_tables/lookup_marking_profile.sql:/docker-entrypoint-initdb.d/910-lookup_marking_profile.sql
      - ./structure/ci2027/lookup_tables/lookup_terrain_form.sql:/docker-entrypoint-initdb.d/910-lookup_terrain_form.sql
      - ./structure/ci2027/lookup_tables/lookup_management_type.sql:/docker-entrypoint-initdb.d/910-lookup_management_type.sql
      - ./structure/ci2027/lookup_tables/lookup_harvesting_method.sql:/docker-entrypoint-initdb.d/910-lookup_harvesting_method.sql
      - ./structure/ci2027/lookup_tables/lookup_stand_phase.sql:/docker-entrypoint-initdb.d/910-lookup_stand_phase.sql
      - ./structure/ci2027/lookup_tables/lookup_stand_layer.sql:/docker-entrypoint-initdb.d/910-lookup_stand_layer.sql
      - ./structure/ci2027/lookup_tables/lookup_trees_less_4meter_count_factor.sql:/docker-entrypoint-initdb.d/910-lookup_trees_less_4meter_count_factor.sql
      - ./structure/ci2027/lookup_tables/lookup_trees_less_4meter_layer.sql:/docker-entrypoint-initdb.d/910-lookup_trees_less_4meter_layer.sql
      - ./structure/ci2027/lookup_tables/lookup_trees_less_4meter_mirrored.sql:/docker-entrypoint-initdb.d/910-lookup_trees_less_4meter_mirrored.sql
      - ./structure/ci2027/lookup_tables/lookup_trees_less_4meter_origin.sql:/docker-entrypoint-initdb.d/910-lookup_trees_less_4meter_origin.sql
      - ./structure/ci2027/lookup_tables/lookup_tree_state.sql:/docker-entrypoint-initdb.d/910-lookup_tree_state.sql
      - ./structure/ci2027/lookup_tables/lookup_tree_species.sql:/docker-entrypoint-initdb.d/910-lookup_tree_species.sql
      - ./structure/ci2027/lookup_tables/lookup_stem_breakage.sql:/docker-entrypoint-initdb.d/910-lookup_stem_breakage.sql
      - ./structure/ci2027/lookup_tables/lookup_stem_form.sql:/docker-entrypoint-initdb.d/910-lookup_stem_form.sql
      - ./structure/ci2027/lookup_tables/lookup_pruning.sql:/docker-entrypoint-initdb.d/910-lookup_pruning.sql
      - ./structure/ci2027/lookup_tables/lookup_tree_species_group.sql:/docker-entrypoint-initdb.d/910-lookup_tree_species_group.sql
      - ./structure/ci2027/lookup_tables/lookup_dead_wood_type.sql:/docker-entrypoint-initdb.d/910-lookup_dead_wood_type.sql
      - ./structure/ci2027/lookup_tables/lookup_decomposition.sql:/docker-entrypoint-initdb.d/910-lookup_decomposition.sql
      - ./structure/ci2027/lookup_tables/lookup_terrain.sql:/docker-entrypoint-initdb.d/910-lookup_terrain.sql
      - ./structure/ci2027/lookup_tables/lookup_edge_state.sql:/docker-entrypoint-initdb.d/910-lookup_edge_state.sql
      - ./structure/ci2027/lookup_tables/lookup_edge_type.sql:/docker-entrypoint-initdb.d/910-lookup_edge_type.sql
      - ./structure/ci2027/lookup_tables/lookup_gnss_quality.sql:/docker-entrypoint-initdb.d/910-lookup_gnss_quality.sql
      - ./structure/ci2027/lookup_tables/lookup_browsing.sql:/docker-entrypoint-initdb.d/910-lookup_browsing.sql
      - ./structure/ci2027/lookup_tables/lookup_tree_size_class.sql:/docker-entrypoint-initdb.d/910-lookup_tree_size_class.sql


      - ./structure/ci2027/tables/cluster.sql:/docker-entrypoint-initdb.d/919-cluster.sql
      - ./structure/ci2027/tables/plot.sql:/docker-entrypoint-initdb.d/919-plot.sql
      - ./structure/ci2027/tables/plot_location.sql:/docker-entrypoint-initdb.d/920-plot_location.sql
      
      
      - ./structure/ci2027/tables/wzp_tree.sql:/docker-entrypoint-initdb.d/922-wzp_tree.sql
      - ./structure/ci2027/tables/position.sql:/docker-entrypoint-initdb.d/922-position.sql
      - ./structure/ci2027/tables/edge.sql:/docker-entrypoint-initdb.d/922-edge.sql
      - ./structure/ci2027/tables/sapling_1m.sql:/docker-entrypoint-initdb.d/922-sapling_1m.sql
      - ./structure/ci2027/tables/sapling_2m.sql:/docker-entrypoint-initdb.d/922-sapling_2m.sql
      - ./structure/ci2027/tables/deadwood.sql:/docker-entrypoint-initdb.d/922-deadwood.sql

      

      - ./structure/ci2027/trigger.sql:/docker-entrypoint-initdb.d/930-trigger.sql
      

      # Views
      - ./structure/ci2027/view/qgis.sql:/docker-entrypoint-initdb.d/923-qgis.sql


       # TMP
      - ./ci2027-db-structure/NFI2022/schema.sql:/docker-entrypoint-initdb.d/998-schema.sql
      - ./ci2027-db-structure/NFI2022/code_bwineu.sql:/docker-entrypoint-initdb.d/999-code_bwineu.sql
      - ./ci2027-db-structure/NFI2022/bwineu_structure.sql:/docker-entrypoint-initdb.d/999-bwineu_structure.sql

      ### Test Setup to be used by automated tests
      - ./structure/default_user.sql:/docker-entrypoint-initdb.d/99-default_user.sql
      #- ./default/views.sql:/docker-entrypoint-initdb.d/99-default-views.sql
      

      # GET DEPRECATED
      #- ./structure/ci2027/functions/get_clusters.sql:/docker-entrypoint-initdb.d/99-get_clusters.sql
      
      # SET
      - ./structure/ci2027/functions/set/plot_location.sql:/docker-entrypoint-initdb.d/99-plot_location.sql

      - ./structure/ci2027/functions/set/wzp_tree.sql:/docker-entrypoint-initdb.d/99-wzp_tree.sql
      - ./structure/ci2027/functions/set/deadwood.sql:/docker-entrypoint-initdb.d/99-deadwood.sql
      - ./structure/ci2027/functions/set/plot.sql:/docker-entrypoint-initdb.d/99-plot.sql
      - ./structure/ci2027/functions/set/position.sql:/docker-entrypoint-initdb.d/99-position.sql
      - ./structure/ci2027/functions/set/sapling_1m.sql:/docker-entrypoint-initdb.d/99-sapling_1m.sql
      - ./structure/ci2027/functions/set/sapling_2m.sql:/docker-entrypoint-initdb.d/99-sapling_2m.sql
      - ./structure/ci2027/functions/set/edges.sql:/docker-entrypoint-initdb.d/99-xedges.sql

      - ./structure/ci2027/functions/set_clusters.sql:/docker-entrypoint-initdb.d/99-set_clusters.sql
      

      - ./structure/ci2027/default_data.sql:/docker-entrypoint-initdb.d/999-default_data.sql

      
      - ./structure/ci2027/functions/authentication.sql:/docker-entrypoint-initdb.d/999-authentication.sql

      #- ./pgdata:/var/lib/postgresql/data

  pgadmin:
    restart: always
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 5050
        SCRIPT_NAME: "/pgadmin"
    ports:
        - "5050:5050"
    links:
        - postgres:${POSTGRES_HOST}
    depends_on:
      - postgrest
    user: root
    volumes:
      - ./pgadmindata:/var/lib/pgadmin

