SET search_path TO private_ci2027_001;

--
-- TOC entry 286 (class 1259 OID 19089)
-- Name: lookup_growth_area; Type: TABLE; Schema: private_ci2027_001; Owner: postgres
--
CREATE TABLE lookup_growth_district AS TABLE lookup_TEMPLATE WITH NO DATA;
ALTER TABLE lookup_growth_district ADD COLUMN abbreviation integer UNIQUE NOT NULL;
ALTER TABLE lookup_growth_district ADD COLUMN states enum_state[];

ALTER TABLE lookup_growth_district ADD COLUMN district_area integer not null;

ALTER TABLE ONLY lookup_growth_district
    ADD CONSTRAINT FK_LookupGrowthArea FOREIGN KEY (district_area) REFERENCES lookup_growth_area(abbreviation);


INSERT INTO lookup_growth_district (abbreviation, name_de, name_en, district_area, states) VALUES
	(199, 'alle Wb in Wg=1=Schleswig-Holstein Nordwest', 'alle Wb in Wg=1=Schleswig-Holstein Nordwest', 1, '{SH,HH}'),
	(299, 'alle Wb in Wg=2=Jungmoränenlandschaft Schleswig-Holstein Ost / Nordwest-Mecklenburg', 'alle Wb in Wg=2=Jungmoränenlandschaft Schleswig-Holstein Ost / Nordwest-Mecklenburg', 2, '{SH,HH,NI,MV}'),
	(399, 'alle Wb in Wg=3=Schleswig-Holstein Südwest', 'alle Wb in Wg=3=Schleswig-Holstein Südwest', 3, '{SH,HH,NI}'),
	(499, 'alle Wb in Wg=4=Mecklenburg-Westvorpommersches Küstenland', 'alle Wb in Wg=4=Mecklenburg-Westvorpommersches Küstenland', 4, '{MV}'),
	(599, 'alle Wb in Wg=5=Ostholsteinisch-Westmecklenburger Jungmoränenland', 'alle Wb in Wg=5=Ostholsteinisch-Westmecklenburger Jungmoränenland', 5, '{BB,MV}'),
	(699, 'alle Wb in Wg=6=(Mittel-) Mecklenburger Jungmoränenland', 'alle Wb in Wg=6=(Mittel-) Mecklenburger Jungmoränenland', 6, '{BB,MV}'),
	(799, 'alle Wb in Wg=7=Ostmecklenburg-Vorpommersches Jungmoränenland', 'alle Wb in Wg=7=Ostmecklenburg-Vorpommersches Jungmoränenland', 7, '{BB}'),
	(899, 'alle Wb in Wg=8=Ostvorpommersches Küstenland', 'alle Wb in Wg=8=Ostvorpommersches Küstenland', 8, '{MV}'),
	(999, 'alle Wb in Wg=9=Nordostbrandenburger Jungmoränenland (Mittelbrandenburger Jungmoränenland)', 'alle Wb in Wg=9=Nordostbrandenburger Jungmoränenland (Mittelbrandenburger Jungmoränenland)', 9, '{BE,BB,MV}'),
	(1099, 'alle Wb in Wg=10=Ostmecklenburg-Nordbrandenburger Jungmoränenland (Nordbrandenburger Jungmoränenland', 'alle Wb in Wg=10=Ostmecklenburg-Nordbrandenburger Jungmoränenland (Nordbrandenburger Jungmoränenland', 10, '{BB,MV}'),
	(1199, 'alle Wb in Wg=11=Ostniedersächsisch-altmärkisches Altmoränenland (Westprignitz-Altmärkisches Altmorä', 'alle Wb in Wg=11=Ostniedersächsisch-altmärkisches Altmoränenland (Westprignitz-Altmärkisches Altmorä', 11, '{NI,BB,MV,ST}'),
	(1299, 'alle Wb in Wg=12=Südost-Holsteinisch-Südwestmecklenburger Altmoränenland', 'alle Wb in Wg=12=Südost-Holsteinisch-Südwestmecklenburger Altmoränenland', 12, '{SH,NI,BB,MV}'),
	(1399, 'alle Wb in Wg=13=Ostniedersächsisches Tiefland', 'alle Wb in Wg=13=Ostniedersächsisches Tiefland', 13, '{SH,HH,NI,BB,MV,ST}'),
	(1499, 'alle Wb in Wg=14=Niedersächsischer Küstenraum', 'alle Wb in Wg=14=Niedersächsischer Küstenraum', 14, '{NI,HB}'),
	(1599, 'alle Wb in Wg=15=Mittelwestniedersächsisches Tiefland', 'alle Wb in Wg=15=Mittelwestniedersächsisches Tiefland', 15, '{NI,HB,NW}'),
	(1699, 'alle Wb in Wg=16=Westfälische Bucht', 'alle Wb in Wg=16=Westfälische Bucht', 16, '{NI,NW}'),
	(1799, 'alle Wb in Wg=17=Weserbergland', 'alle Wb in Wg=17=Weserbergland', 17, '{NI,NW,HE}'),
	(1899, 'alle Wb in Wg=18=Nordwestdeutsche Berglandschwelle', 'alle Wb in Wg=18=Nordwestdeutsche Berglandschwelle', 18, '{NI,NW,ST}'),
	(1999, 'alle Wb in Wg=19=Nordwestliches Harzvorland', 'alle Wb in Wg=19=Nordwestliches Harzvorland', 19, '{NI,ST}'),
	(2099, 'alle Wb in Wg=20=Nordöstliche Harzvorländer', 'alle Wb in Wg=20=Nordöstliche Harzvorländer', 20, '{ST}'),
	(2199, 'alle Wb in Wg=21=Sachsen-Anhaltinische Löss-Ebene', 'alle Wb in Wg=21=Sachsen-Anhaltinische Löss-Ebene', 21, '{SN,ST}'),
	(2299, 'alle Wb in Wg=22=Mittleres nordostdeutsches Altmoränenland', 'alle Wb in Wg=22=Mittleres nordostdeutsches Altmoränenland', 22, '{BB,SN,ST}'),
	(2399, 'alle Wb in Wg=23=Hoher Fläming', 'alle Wb in Wg=23=Hoher Fläming', 23, '{BB,ST}'),
	(2499, 'alle Wb in Wg=24=Mittelbrandenburger Talsand- und Moränenland', 'alle Wb in Wg=24=Mittelbrandenburger Talsand- und Moränenland', 24, '{BB,SN,ST}'),
	(2599, 'alle Wb in Wg=25=Düben-Niederlausitzer Altmoränenland', 'alle Wb in Wg=25=Düben-Niederlausitzer Altmoränenland', 25, '{SN}'),
	(2699, 'alle Wb in Wg=26=Lausitzer Löss-Hügelland', 'alle Wb in Wg=26=Lausitzer Löss-Hügelland', 26, '{SN}'),
	(2799, 'alle Wb in Wg=27=Zittauer Gebirge', 'alle Wb in Wg=27=Zittauer Gebirge', 27, '{SN}'),
	(2899, 'alle Wb in Wg=28=Oberlausitzer Bergland', 'alle Wb in Wg=28=Oberlausitzer Bergland', 28, '{SN}'),
	(2999, 'alle Wb in Wg=29=Elbsandsteingebirge', 'alle Wb in Wg=29=Elbsandsteingebirge', 29, '{SN}'),
	(3099, 'alle Wb in Wg=30=Westlausitzer Platte und Elbtalzone', 'alle Wb in Wg=30=Westlausitzer Platte und Elbtalzone', 30, '{SN}'),
	(4001, 'Niedersauerland', 'Niedersauerland', 40, '{NW}'),
	(3199, 'alle Wb in Wg=31=Sächsisch-Thüringisches Löss-Hügelland', 'alle Wb in Wg=31=Sächsisch-Thüringisches Löss-Hügelland', 31, '{SN,ST,TH}'),
	(3299, 'alle Wb in Wg=32=Leipziger Sandlöss-Ebene', 'alle Wb in Wg=32=Leipziger Sandlöss-Ebene', 32, '{SN,ST,TH}'),
	(3399, 'alle Wb in Wg=33=Ostthüringisches Trias-Hügelland', 'alle Wb in Wg=33=Ostthüringisches Trias-Hügelland', 33, '{ST,TH}'),
	(3499, 'alle Wb in Wg=34=Thüringer Becken', 'alle Wb in Wg=34=Thüringer Becken', 34, '{ST,TH}'),
	(3599, 'alle Wb in Wg=35=Nordthüringisches Trias-Hügelland', 'alle Wb in Wg=35=Nordthüringisches Trias-Hügelland', 35, '{NI,ST,TH}'),
	(3699, 'alle Wb in Wg=36=Harz', 'alle Wb in Wg=36=Harz', 36, '{NI,ST,TH}'),
	(3799, 'alle Wb in Wg=37=Mitteldeutsches Trias-Berg- und Hügelland', 'alle Wb in Wg=37=Mitteldeutsches Trias-Berg- und Hügelland', 37, '{NI,NW,HE,TH}'),
	(3899, 'alle Wb in Wg=38=Nordwesthessisches Bergland', 'alle Wb in Wg=38=Nordwesthessisches Bergland', 38, '{NI,NW,HE}'),
	(3999, 'alle Wb in Wg=39=Nördliches hessisches Schiefergebirge', 'alle Wb in Wg=39=Nördliches hessisches Schiefergebirge', 39, '{NW,HE}'),
	(4099, 'alle Wb in Wg=40=Sauerland', 'alle Wb in Wg=40=Sauerland', 40, '{NW,HE,RP}'),
	(4199, 'alle Wb in Wg=41=Bergisches Land', 'alle Wb in Wg=41=Bergisches Land', 41, '{NW,RP}'),
	(4299, 'alle Wb in Wg=42=Niederrheinisches Tiefland', 'alle Wb in Wg=42=Niederrheinisches Tiefland', 42, '{NW}'),
	(4399, 'alle Wb in Wg=43=Niederrheinische Bucht', 'alle Wb in Wg=43=Niederrheinische Bucht', 43, '{NW,RP}'),
	(4499, 'alle Wb in Wg=44=Nordwesteifel', 'alle Wb in Wg=44=Nordwesteifel', 44, '{NW,RP}'),
	(4599, 'alle Wb in Wg=45=Osteifel', 'alle Wb in Wg=45=Osteifel', 45, '{NW,RP}'),
	(4699, 'alle Wb in Wg=46=Mittelrheintal', 'alle Wb in Wg=46=Mittelrheintal', 46, '{HE,RP}'),
	(4799, 'alle Wb in Wg=47=Westerwald', 'alle Wb in Wg=47=Westerwald', 47, '{NW,HE,RP}'),
	(4899, 'alle Wb in Wg=48=Taunus', 'alle Wb in Wg=48=Taunus', 48, '{HE,RP}'),
	(4999, 'alle Wb in Wg=49=Wetterau  und Giessener Becken', 'alle Wb in Wg=49=Wetterau  und Giessener Becken', 49, '{HE}'),
	(5099, 'alle Wb in Wg=50=Vogelsberg und östlich angrenzende Sandsteingebiete', 'alle Wb in Wg=50=Vogelsberg und östlich angrenzende Sandsteingebiete', 50, '{HE}'),
	(5199, 'alle Wb in Wg=51=Rhön', 'alle Wb in Wg=51=Rhön', 51, '{HE,BY,TH}'),
	(5299, 'alle Wb in Wg=52=Südthüringisches-Oberfränkisches Trias-Hügelland', 'alle Wb in Wg=52=Südthüringisches-Oberfränkisches Trias-Hügelland', 52, '{BY,TH}'),
	(5399, 'alle Wb in Wg=53=Thüringer Gebirge', 'alle Wb in Wg=53=Thüringer Gebirge', 53, '{BY,TH}'),
	(5499, 'alle Wb in Wg=54=Vogtland', 'alle Wb in Wg=54=Vogtland', 54, '{BY,SN,TH}'),
	(5599, 'alle Wb in Wg=55=Erzgebirgsvorland', 'alle Wb in Wg=55=Erzgebirgsvorland', 55, '{SN,TH}'),
	(5699, 'alle Wb in Wg=56=Erzgebirge', 'alle Wb in Wg=56=Erzgebirge', 56, '{SN}'),
	(5799, 'alle Wb in Wg=57=Frankenwald, Fichtelgebirge und Steinwald', 'alle Wb in Wg=57=Frankenwald, Fichtelgebirge und Steinwald', 57, '{BY,TH}'),
	(5899, 'alle Wb in Wg=58=Oberpfälzer Wald', 'alle Wb in Wg=58=Oberpfälzer Wald', 58, '{BY}'),
	(5999, 'alle Wb in Wg=59=Oberpfälzer Becken- und Hügelland', 'alle Wb in Wg=59=Oberpfälzer Becken- und Hügelland', 59, '{BY}'),
	(6099, 'alle Wb in Wg=60=Frankenalb und Oberpfälzer Jura', 'alle Wb in Wg=60=Frankenalb und Oberpfälzer Jura', 60, '{BW,BY}'),
	(6199, 'alle Wb in Wg=61=Fränkischer Keuper und Albvorland', 'alle Wb in Wg=61=Fränkischer Keuper und Albvorland', 61, '{BW,BY,TH}'),
	(6299, 'alle Wb in Wg=62=Fränkische Platte', 'alle Wb in Wg=62=Fränkische Platte', 62, '{BW,BY,TH}'),
	(6399, 'alle Wb in Wg=63=Spessart', 'alle Wb in Wg=63=Spessart', 63, '{HE,BW,BY}'),
	(6499, 'alle Wb in Wg=64=Odenwald', 'alle Wb in Wg=64=Odenwald', 64, '{HE,BW,BY}'),
	(6599, 'alle Wb in Wg=65=Oberrheinisches Tiefland und Rhein-Main-Ebene', 'alle Wb in Wg=65=Oberrheinisches Tiefland und Rhein-Main-Ebene', 65, '{HE,RP,BW,BY}'),
	(6699, 'alle Wb in Wg=66=Hunsrück', 'alle Wb in Wg=66=Hunsrück', 66, '{RP,SL}'),
	(6799, 'alle Wb in Wg=67=Moseltal', 'alle Wb in Wg=67=Moseltal', 67, '{RP}'),
	(6899, 'alle Wb in Wg=68=Gutland', 'alle Wb in Wg=68=Gutland', 68, '{RP}'),
	(6999, 'alle Wb in Wg=69=Saarländisch-Pfälzisches Muschelkalkgebiet', 'alle Wb in Wg=69=Saarländisch-Pfälzisches Muschelkalkgebiet', 69, '{RP,SL}'),
	(7099, 'alle Wb in Wg=70=Saar-Nahe Bergland', 'alle Wb in Wg=70=Saar-Nahe Bergland', 70, '{RP,SL}'),
	(7199, 'alle Wb in Wg=71=Westricher Moorniederung', 'alle Wb in Wg=71=Westricher Moorniederung', 71, '{RP,SL}'),
	(7299, 'alle Wb in Wg=72=Pfälzerwald', 'alle Wb in Wg=72=Pfälzerwald', 72, '{RP}'),
	(7399, 'alle Wb in Wg=73=Schwarzwald', 'alle Wb in Wg=73=Schwarzwald', 73, '{BW}'),
	(7499, 'alle Wb in Wg=74=Baar-Wutach', 'alle Wb in Wg=74=Baar-Wutach', 74, '{BW}'),
	(7599, 'alle Wb in Wg=75=Neckarland', 'alle Wb in Wg=75=Neckarland', 75, '{BW,BY}'),
	(7699, 'alle Wb in Wg=76=Schwäbische Alb', 'alle Wb in Wg=76=Schwäbische Alb', 76, '{BW,BY}'),
	(7799, 'alle Wb in Wg=77=Südwestdeutsches Alpenvorland', 'alle Wb in Wg=77=Südwestdeutsches Alpenvorland', 77, '{BW,BY}'),
	(7899, 'alle Wb in Wg=78=Tertiäres Hügelland', 'alle Wb in Wg=78=Tertiäres Hügelland', 78, '{BW,BY}'),
	(7999, 'alle Wb in Wg=79=Bayerischer Wald', 'alle Wb in Wg=79=Bayerischer Wald', 79, '{BY}'),
	(8099, 'alle Wb in Wg=80=Schwäbisch-Bayerische Schotterplatten- und Altmoränenlandschaft', 'alle Wb in Wg=80=Schwäbisch-Bayerische Schotterplatten- und Altmoränenlandschaft', 80, '{BW,BY}'),
	(8199, 'alle Wb in Wg=81=Schwäbisch-Bayerische Jungmoräne und Molassevorberge', 'alle Wb in Wg=81=Schwäbisch-Bayerische Jungmoräne und Molassevorberge', 81, '{BW,BY}'),
	(8299, 'alle Wb in Wg=82=Bayerische Alpen', 'alle Wb in Wg=82=Bayerische Alpen', 82, '{BW,BY}'),
	(9999, 'alle Wuchsbezirke', 'alle Wuchsbezirke', 99, '{SH,HH,NI,NI,HB,NW,HE,RP,BW,BY,SL,BE,BB,MV,SN,ST,TH}'),
	(101, 'Westküsten-Marschen u. Inseln', 'Westküsten-Marschen u. Inseln', 1, '{SH,HH}'),
	(102, 'Westküstennahe Geest', 'Westküstennahe Geest', 1, '{SH}'),
	(103, 'Schleswiger Vorgeest', 'Schleswiger Vorgeest', 1, '{SH}'),
	(201, 'Nördliches Hügelland', 'Nördliches Hügelland', 2, '{SH}'),
	(202, 'Mittleres Hügelland', 'Mittleres Hügelland', 2, '{SH}'),
	(203, 'Oldesloer-Gadebuscher Grundmoräne', 'Oldesloer-Gadebuscher Grundmoräne', 2, '{SH,HH,MV}'),
	(204, 'Südliche Geest mit Vorgeest', 'Südliche Geest mit Vorgeest', 2, '{SH,HH,NI}'),
	(205, 'Lübecker Sand-Zwischenebene', 'Lübecker Sand-Zwischenebene', 2, '{SH,MV}'),
	(301, 'Holsteiner Elbmarschen', 'Holsteiner Elbmarschen', 3, '{SH,HH,NI}'),
	(302, 'Holsteiner Geest', 'Holsteiner Geest', 3, '{SH,HH}'),
	(303, 'Holsteiner Vorgeest', 'Holsteiner Vorgeest', 3, '{SH}'),
	(401, 'Boltenhagener Grund- (Wellen-) moräne', 'Boltenhagener Grund- (Wellen-) moräne', 4, '{MV}'),
	(402, 'Wismarer Wellen- und Hügelmoräne', 'Wismarer Wellen- und Hügelmoräne', 4, '{MV}'),
	(403, 'Moränenplatteninsel Poel', 'Moränenplatteninsel Poel', 4, '{MV}'),
	(404, 'Höhenzug Kühlung', 'Höhenzug Kühlung', 4, '{MV}'),
	(405, 'Lichtenhagener Flachmoräne', 'Lichtenhagener Flachmoräne', 4, '{MV}'),
	(406, 'Hinrichsdorfer Flachmoräne', 'Hinrichsdorfer Flachmoräne', 4, '{MV}'),
	(407, 'Altenpleener Flachmoräne mit Wellenmoränen-Teilareal (SO von Barth)', 'Altenpleener Flachmoräne mit Wellenmoränen-Teilareal (SO von Barth)', 4, '{MV}'),
	(408, 'Graal-Müritzer Sandniederung', 'Graal-Müritzer Sandniederung', 4, '{MV}'),
	(409, 'Fuhlendorfer Sandniederung', 'Fuhlendorfer Sandniederung', 4, '{MV}'),
	(410, 'Darss-Hiddenseer Küstensandniederung mit Teilarealen: Borner Altniederung und Dornbusch-Hügelmoräne', 'Darss-Hiddenseer Küstensandniederung mit Teilarealen: Borner Altniederung und Dornbusch-Hügelmoräne', 4, '{MV}'),
	(411, 'Westrügener Flachmoräne im Wechsel mit Küstensand- und -schlickniederung', 'Westrügener Flachmoräne im Wechsel mit Küstensand- und -schlickniederung', 4, '{MV}'),
	(412, 'Nordrügener Flachmoräne mit Teilareal Küstensandniederung', 'Nordrügener Flachmoräne mit Teilareal Küstensandniederung', 4, '{MV}'),
	(413, 'Jasmunder Höhenmoräne mit Arkonasporn-Absprengsel und Garnitz Teilareal', 'Jasmunder Höhenmoräne mit Arkonasporn-Absprengsel und Garnitz Teilareal', 4, '{MV}'),
	(414, 'Mittelrügener Platten- und Hügelmoräne', 'Mittelrügener Platten- und Hügelmoräne', 4, '{MV}'),
	(501, 'Westenbrügger Grund- (Wellen-) moräne (II)', 'Westenbrügger Grund- (Wellen-) moräne (II)', 5, '{MV}'),
	(502, 'Schweriner See mit Randmooren und - niederungen und Moräneninseln als Einsprengsel', 'Schweriner See mit Randmooren und - niederungen und Moräneninseln als Einsprengsel', 5, '{MV}'),
	(503, 'Brüler Grund- (Wellen-) moräne', 'Brüler Grund- (Wellen-) moräne', 5, '{MV}'),
	(504, 'Neukloster-Teterower-Hügelmoränenbogen (IV) mit Teilareal Krakower See', 'Neukloster-Teterower-Hügelmoränenbogen (IV) mit Teilareal Krakower See', 5, '{MV}'),
	(505, 'Bützower Grund- (Wellen-) moräne (II)', 'Bützower Grund- (Wellen-) moräne (II)', 5, '{MV}'),
	(506, 'Warnowtal', 'Warnowtal', 5, '{MV}'),
	(507, 'Sanitz-Güstrower Grund- (Wellen-) moräne (III)', 'Sanitz-Güstrower Grund- (Wellen-) moräne (III)', 5, '{MV}'),
	(508, 'Oberes Recknitztal', 'Oberes Recknitztal', 5, '{MV}'),
	(509, 'Schwinzer Sandhochfläche mit Teilareal Goldberger See', 'Schwinzer Sandhochfläche mit Teilareal Goldberger See', 5, '{MV}'),
	(510, 'Gnoiener Grund- (Wellen-) moräne (II)', 'Gnoiener Grund- (Wellen-) moräne (II)', 5, '{MV}'),
	(511, 'Recknitz-Trebeltal', 'Recknitz-Trebeltal', 5, '{MV}'),
	(512, 'Malchiner Peenetal', 'Malchiner Peenetal', 5, '{MV}'),
	(513, 'Richtenberger Flachmoräne', 'Richtenberger Flachmoräne', 5, '{MV}'),
	(514, 'Goldberger Grund- (Wellen-) moräne (IV)', 'Goldberger Grund- (Wellen-) moräne (IV)', 5, '{MV}'),
	(515, 'Lübzer Plattenmoräne', 'Lübzer Plattenmoräne', 5, '{BB,MV}'),
	(516, 'Parchim-Meyenburger Sandhochfläche (V)', 'Parchim-Meyenburger Sandhochfläche (V)', 5, '{BB,MV}'),
	(517, 'Sülter Sandhochfläche', 'Sülter Sandhochfläche', 5, '{MV}'),
	(601, 'Petersdorfer Sandhochfläche mit Teilareal Plauer See', 'Petersdorfer Sandhochfläche mit Teilareal Plauer See', 6, '{MV}'),
	(602, 'Malchower Grund- (Wellen-) moräne (Freyensteiner Platte)', 'Malchower Grund- (Wellen-) moräne (Freyensteiner Platte)', 6, '{BB,MV}'),
	(603, 'Warener Sandhochfläche mit See-Teilarealen', 'Warener Sandhochfläche mit See-Teilarealen', 6, '{MV}'),
	(1303, 'Ost-Heide', 'Ost-Heide', 13, '{NI,ST}'),
	(1304, 'Stromland zwischen Lenzen und Boitzenburg', 'Stromland zwischen Lenzen und Boitzenburg', 13, '{HH,NI,BB,MV}'),
	(604, 'Die Müritz mit Rand; mit Teilareal Specker See-(küsten-)niederung sowie Randmooren und -niederungen', 'Die Müritz mit Rand; mit Teilareal Specker See-(küsten-)niederung sowie Randmooren und -niederungen', 6, '{MV}'),
	(605, 'Rheinsberg-Mirower Seenmoräne (Rheinsberger seenreiche Jungmoräne)', 'Rheinsberg-Mirower Seenmoräne (Rheinsberger seenreiche Jungmoräne)', 6, '{BB,MV}'),
	(606, 'Düsterförder Sandhochfläche', 'Düsterförder Sandhochfläche', 6, '{MV}'),
	(607, 'Feldberger Hügelmoräne', 'Feldberger Hügelmoräne', 6, '{BB,MV}'),
	(701, 'Behrenhoffer Plattenmoräne', 'Behrenhoffer Plattenmoräne', 7, '{MV}'),
	(702, 'Jarmener Peenetalmoor', 'Jarmener Peenetalmoor', 7, '{MV}'),
	(703, 'Kriener Flachmoräne', 'Kriener Flachmoräne', 7, '{MV}'),
	(704, 'Stavenhagener Grund- (Wellen-) moräne mit See-Teilarealen', 'Stavenhagener Grund- (Wellen-) moräne mit See-Teilarealen', 7, '{MV}'),
	(705, 'Plastener Hügelmoräne', 'Plastener Hügelmoräne', 7, '{MV}'),
	(706, 'Neubrandenburger Talmoornetz mit Teilareal Tollense-See', 'Neubrandenburger Talmoornetz mit Teilareal Tollense-See', 7, '{MV}'),
	(707, 'Roggenhagener Grund- (Wellen-) moräne', 'Roggenhagener Grund- (Wellen-) moräne', 7, '{MV}'),
	(708, 'Burg Stargarder Grund- (Wellen-) moräne', 'Burg Stargarder Grund- (Wellen-) moräne', 7, '{MV}'),
	(709, 'Helpt-Brohmer Höhenmoräne', 'Helpt-Brohmer Höhenmoräne', 7, '{BB,MV}'),
	(3723, 'Hainich-Dün', 'Hainich-Dün', 37, '{HE,TH}'),
	(801, 'Ostrügener Platten- und Hügelmoräne im Wechsel mit Küstenniederungen mit Granitz-Teilareal; mit', 'Ostrügener Platten- und Hügelmoräne im Wechsel mit Küstenniederungen mit Granitz-Teilareal; mit', 8, '{MV}'),
	(802, 'Reinberger Platten- und Flachmoräne', 'Reinberger Platten- und Flachmoräne', 8, '{MV}'),
	(803, 'Ziese-Talmoor', 'Ziese-Talmoor', 8, '{MV}'),
	(804, 'Lubminer Plattenmoräne', 'Lubminer Plattenmoräne', 8, '{MV}'),
	(805, 'Ostwolgaster Plattenmoräne mit Teilareal Gnitz', 'Ostwolgaster Plattenmoräne mit Teilareal Gnitz', 8, '{MV}'),
	(806, 'Peenemünder Küstenniederung', 'Peenemünder Küstenniederung', 8, '{MV}'),
	(807, 'Kernusedomer Plattenmoränen und Küstenmoorniederungen', 'Kernusedomer Plattenmoränen und Küstenmoorniederungen', 8, '{MV}'),
	(808, 'Greifswald-Lassaner Platten- und Flachmoräne', 'Greifswald-Lassaner Platten- und Flachmoräne', 8, '{MV}'),
	(809, 'Anklamer Peenemündungsmoor', 'Anklamer Peenemündungsmoor', 8, '{MV}'),
	(810, 'Torgelower Sandzwischenebene', 'Torgelower Sandzwischenebene', 8, '{MV}'),
	(811, 'Friedländer Moorniederung (Grosse Friedländer Wiese)', 'Friedländer Moorniederung (Grosse Friedländer Wiese)', 8, '{MV}'),
	(812, 'Pampower Hügelmoräne (mit Küstenkontakt auf polnischer Seite)', 'Pampower Hügelmoräne (mit Küstenkontakt auf polnischer Seite)', 8, '{MV}'),
	(901, 'Gramzower Grund- (Wellen-) moräne (Gramzower lehmreiche Jungmoräne)', 'Gramzower Grund- (Wellen-) moräne (Gramzower lehmreiche Jungmoräne)', 9, '{BB,MV}'),
	(902, 'Randow-Bruch (Randowtal)', 'Randow-Bruch (Randowtal)', 9, '{BB,MV}'),
	(903, 'Penkuner Grund- (Wellen-) moräne (Penkuner lehmreiche Jungmoräne)', 'Penkuner Grund- (Wellen-) moräne (Penkuner lehmreiche Jungmoräne)', 9, '{BB,MV}'),
	(904, 'Schwedter Terrasse', 'Schwedter Terrasse', 9, '{BB}'),
	(905, 'Oderaue (extra makrochorisch), Teilstück', 'Oderaue (extra makrochorisch), Teilstück', 9, '{BB}'),
	(906, 'Neuenhagener Oderinsel', 'Neuenhagener Oderinsel', 9, '{BB}'),
	(907, 'Oderbruch mit Wriezener Terrasse', 'Oderbruch mit Wriezener Terrasse', 9, '{BB}'),
	(908, 'Strausberger Platte', 'Strausberger Platte', 9, '{BE,BB}'),
	(909, 'Buckower Stobber-Durchbruch', 'Buckower Stobber-Durchbruch', 9, '{BB}'),
	(910, 'Seelower Platte', 'Seelower Platte', 9, '{BB}'),
	(911, 'Gellmersdorfer Jungmoränenland', 'Gellmersdorfer Jungmoränenland', 9, '{BB}'),
	(1001, 'Gadower Sander', 'Gadower Sander', 10, '{BB}'),
	(1002, 'Wusterhausener Dossetal', 'Wusterhausener Dossetal', 10, '{BB}'),
	(1003, 'Neuruppiner Platte', 'Neuruppiner Platte', 10, '{BB}'),
	(1004, 'Lindower Rhintal', 'Lindower Rhintal', 10, '{BB}'),
	(1005, 'Granseer Platte', 'Granseer Platte', 10, '{BB}'),
	(1006, 'Rüthnicker Sander', 'Rüthnicker Sander', 10, '{BB}'),
	(1007, 'Oranienburger Talsand', 'Oranienburger Talsand', 10, '{BB}'),
	(1008, 'Templiner sandreiche Jungmoräne', 'Templiner sandreiche Jungmoräne', 10, '{BB}'),
	(1009, 'Angermünde-Strasburger Grund- (Wellen-) moräne (Angermünder lehmreiche Jungmoräne)', 'Angermünde-Strasburger Grund- (Wellen-) moräne (Angermünder lehmreiche Jungmoräne)', 10, '{BB,MV}'),
	(1010, 'Ueckerseenrinne (Ueckertalmoor mit See-Teilarealen)', 'Ueckerseenrinne (Ueckertalmoor mit See-Teilarealen)', 10, '{BB,MV}'),
	(1011, 'Rothemühler Hügelmoräne', 'Rothemühler Hügelmoräne', 10, '{MV}'),
	(1012, 'Brölliner Hügelmoräne', 'Brölliner Hügelmoräne', 10, '{MV}'),
	(1013, 'Bismarker Hügelmoräne', 'Bismarker Hügelmoräne', 10, '{MV}'),
	(1014, 'Kienschorfheide', 'Kienschorfheide', 10, '{BB}'),
	(1015, 'Eichhorster Platte', 'Eichhorster Platte', 10, '{BB}'),
	(1016, 'Wandlitzer Platte', 'Wandlitzer Platte', 10, '{BB}'),
	(1017, 'Basdorfer Sand-Hochfläche', 'Basdorfer Sand-Hochfläche', 10, '{BB}'),
	(1018, 'Eberswalder Talabschnitt', 'Eberswalder Talabschnitt', 10, '{BB}'),
	(1019, 'Tramper Platte', 'Tramper Platte', 10, '{BB}'),
	(1101, 'Diesdorfer Hochfläche', 'Diesdorfer Hochfläche', 11, '{NI,ST}'),
	(1102, 'Ostheide-Altmärkische Platte', 'Ostheide-Altmärkische Platte', 11, '{NI,ST}'),
	(1103, 'Aller-Ohre-Drömling-Niederung', 'Aller-Ohre-Drömling-Niederung', 11, '{NI,ST}'),
	(1104, 'Flechtinger Randplatte', 'Flechtinger Randplatte', 11, '{NI,ST}'),
	(1105, 'Klötzer Hochfläche', 'Klötzer Hochfläche', 11, '{ST}'),
	(1106, 'Letzlinger Platte', 'Letzlinger Platte', 11, '{ST}'),
	(1107, 'Kalbe-Osterburger Niederung und Platten', 'Kalbe-Osterburger Niederung und Platten', 11, '{ST}'),
	(1108, 'Lüchow-Salzwedeler Niederung', 'Lüchow-Salzwedeler Niederung', 11, '{NI,ST}'),
	(1109, 'Seehausen-Gartower Elbaue', 'Seehausen-Gartower Elbaue', 11, '{NI,BB,MV,ST}'),
	(1110, 'Wittenbergesche Elbesand-Terrasse', 'Wittenbergesche Elbesand-Terrasse', 11, '{BB,ST}'),
	(1111, 'Gorlosener Sandniederung', 'Gorlosener Sandniederung', 11, '{BB,MV}'),
	(1112, 'Pritzwalker Platte', 'Pritzwalker Platte', 11, '{BB,MV,ST}'),
	(1201, 'Büchener Sandniederung', 'Büchener Sandniederung', 12, '{SH,NI,MV}'),
	(1202, 'Wittenburger Plattenmoräne', 'Wittenburger Plattenmoräne', 12, '{NI,MV}'),
	(1203, 'Neuhauser Elbauenabschnitt', 'Neuhauser Elbauenabschnitt', 12, '{SH,MV}'),
	(1204, 'Ludwigsluster Sandniederung', 'Ludwigsluster Sandniederung', 12, '{NI,MV}'),
	(1205, 'Quaster Dünenplatte', 'Quaster Dünenplatte', 12, '{MV}'),
	(1206, 'Mallisser Platte', 'Mallisser Platte', 12, '{MV}'),
	(1207, 'Gross Laasch-Wanzlitzer Dünenplatte', 'Gross Laasch-Wanzlitzer Dünenplatte', 12, '{BB,MV}'),
	(1208, 'Balower Platte', 'Balower Platte', 12, '{BB,MV}'),
	(1209, 'Ruhner Höhenmoräne (Ruhner Berge)', 'Ruhner Höhenmoräne (Ruhner Berge)', 12, '{BB,MV}'),
	(1301, 'Hohe Heide', 'Hohe Heide', 13, '{HH,NI}'),
	(1302, 'Süd-Heide', 'Süd-Heide', 13, '{NI}'),
	(1305, 'Lüchower Niederung', 'Lüchower Niederung', 13, '{NI,BB,ST}'),
	(1401, 'Leda-Moorniederung', 'Leda-Moorniederung', 14, '{NI}'),
	(1402, 'Ostfriesisch-Oldenburgische Geest', 'Ostfriesisch-Oldenburgische Geest', 14, '{NI,HB}'),
	(1403, 'Wesermünder Geest', 'Wesermünder Geest', 14, '{NI,HB}'),
	(1404, 'Elbmarschen', 'Elbmarschen', 14, '{SH,HH,NI}'),
	(1501, 'Ems-Hase-Hunte-Geest', 'Ems-Hase-Hunte-Geest', 15, '{NI,HB,NW}'),
	(1502, 'Geest-Mitte', 'Geest-Mitte', 15, '{NI,HB,NW}'),
	(1601, 'Westmünsterland', 'Westmünsterland', 16, '{NI,NW}'),
	(1602, 'Kernmünsterland', 'Kernmünsterland', 16, '{NW}'),
	(1603, 'Ostmünsterland', 'Ostmünsterland', 16, '{NI,NW}'),
	(1604, 'Emscherland', 'Emscherland', 16, '{NW}'),
	(1605, 'Hellwegbörden', 'Hellwegbörden', 16, '{NW}'),
	(1606, 'Paderborner Hochflächen', 'Paderborner Hochflächen', 16, '{NW}'),
	(1701, 'Osnabrück-Ravensberger Berg- und Hügelland', 'Osnabrück-Ravensberger Berg- und Hügelland', 17, '{NI,NW}'),
	(1702, 'Lipper Bergland', 'Lipper Bergland', 17, '{NI,NW}'),
	(1703, 'Egge', 'Egge', 17, '{NW,HE}'),
	(1704, 'Oberwälder Land', 'Oberwälder Land', 17, '{NI,NW,HE}'),
	(1705, 'Unteres Weser-Leine-Bergland', 'Unteres Weser-Leine-Bergland', 17, '{NI,NW}'),
	(1801, 'Niedersächsische Lössbörden', 'Niedersächsische Lössbörden', 18, '{NI,NW}'),
	(1802, 'Ostbraunschweigisches Hügelland', 'Ostbraunschweigisches Hügelland', 18, '{NI,ST}'),
	(1803, 'Ostbraunschweigisches Flachland', 'Ostbraunschweigisches Flachland', 18, '{NI,ST}'),
	(1901, 'Lappwald-Flechtinger Hügelland', 'Lappwald-Flechtinger Hügelland', 19, '{NI,ST}'),
	(1902, 'Braunschweiger Hügelland', 'Braunschweiger Hügelland', 19, '{ST}'),
	(1903, 'Grosses Bruch', 'Grosses Bruch', 19, '{NI,ST}'),
	(1904, 'Hornburg-Osterwiecker Harzvorland', 'Hornburg-Osterwiecker Harzvorland', 19, '{NI,ST}'),
	(2001, 'Halberstädter Harzvorland', 'Halberstädter Harzvorland', 20, '{ST}'),
	(2002, 'Ascherslebener Harzvorland', 'Ascherslebener Harzvorland', 20, '{ST}'),
	(2003, 'Hettstedter Harzvorland', 'Hettstedter Harzvorland', 20, '{ST}'),
	(2004, 'Löbejüner Porphyr-Platte', 'Löbejüner Porphyr-Platte', 20, '{ST}'),
	(2101, 'Magdeburger Börde', 'Magdeburger Börde', 21, '{ST}'),
	(2102, 'Bode-Niederung', 'Bode-Niederung', 21, '{ST}'),
	(2103, 'Köthener Löss-Ebene', 'Köthener Löss-Ebene', 21, '{SN,ST}'),
	(2104, 'Schkeuditz-Lützener Sandlöss-Ebene', 'Schkeuditz-Lützener Sandlöss-Ebene', 21, '{SN,ST}'),
	(2105, 'Elster-Saale-Aue', 'Elster-Saale-Aue', 21, '{SN,ST}'),
	(2106, 'Weissenfelser Löss-Hügelland', 'Weissenfelser Löss-Hügelland', 21, '{SN,ST}'),
	(2201, 'Stendaler Platte', 'Stendaler Platte', 22, '{ST}'),
	(2202, 'Elbe-Tangerwinkel-Niederung', 'Elbe-Tangerwinkel-Niederung', 22, '{ST}'),
	(2203, 'Colbitzer Platte', 'Colbitzer Platte', 22, '{ST}'),
	(2204, 'Magdeburg-Wittenberger Elbaue', 'Magdeburg-Wittenberger Elbaue', 22, '{BB,SN,ST}'),
	(2205, 'Möckern-Ziesarsche Platte', 'Möckern-Ziesarsche Platte', 22, '{BB,ST}'),
	(2206, 'Mosigkauer Platte', 'Mosigkauer Platte', 22, '{ST}'),
	(2207, 'Tieflands-Muldeaue', 'Tieflands-Muldeaue', 22, '{SN,ST}'),
	(2208, 'Elbe-Muldewinkel-Niederung', 'Elbe-Muldewinkel-Niederung', 22, '{ST}'),
	(2209, 'Gräfenheinicher Heiderandplatte', 'Gräfenheinicher Heiderandplatte', 22, '{SN,ST}'),
	(2210, 'Bitterfeld-Badrinaer-Randplatte (Badrinaer Randplatte)', 'Bitterfeld-Badrinaer-Randplatte (Badrinaer Randplatte)', 22, '{SN,ST}'),
	(2211, 'Niemegker Flämingrand-Sand-Hochfläche', 'Niemegker Flämingrand-Sand-Hochfläche', 22, '{BB}'),
	(2212, 'Jüterboger Flämingrücken', 'Jüterboger Flämingrücken', 22, '{BB,ST}'),
	(2213, 'Luckauer Platte', 'Luckauer Platte', 22, '{BB}'),
	(2214, 'Öhnaer Sandlöss-Riegel', 'Öhnaer Sandlöss-Riegel', 22, '{BB}'),
	(2215, 'Zellendorfer Flämingrandplatte', 'Zellendorfer Flämingrandplatte', 22, '{BB,ST}'),
	(2216, 'Schweinitzer Elbe-Elster-Sandterrasse', 'Schweinitzer Elbe-Elster-Sandterrasse', 22, '{BB,ST}'),
	(2217, 'Elbe-Elsterwinkel-Sandterrasse (Annaburger Elbe-Elsterwinkel-Sand-Terrasse)', 'Elbe-Elsterwinkel-Sandterrasse (Annaburger Elbe-Elsterwinkel-Sand-Terrasse)', 22, '{BB,ST}'),
	(2218, '(Herzberger) Elstertal', '(Herzberger) Elstertal', 22, '{BB,ST}'),
	(2301, 'Nedlitzer Flämingrandplatte (Altmoränenplatte)', 'Nedlitzer Flämingrandplatte (Altmoränenplatte)', 23, '{BB,ST}'),
	(2302, 'Wiesenburger Hochfläming (Wiesenburger Fläminghochfläche)', 'Wiesenburger Hochfläming (Wiesenburger Fläminghochfläche)', 23, '{BB,ST}'),
	(2401, 'Schollener Platte', 'Schollener Platte', 24, '{BB,ST}'),
	(2402, 'Elbe-Havelwinkel-Niederung', 'Elbe-Havelwinkel-Niederung', 24, '{BB,ST}'),
	(2403, 'Fiener Bruch', 'Fiener Bruch', 24, '{BB,ST}'),
	(2404, 'Rogäsener Platte (Rogäser Platte)', 'Rogäsener Platte (Rogäser Platte)', 24, '{BB,ST}'),
	(2405, 'Premnitzer Talsand und Platten', 'Premnitzer Talsand und Platten', 24, '{BB,ST}'),
	(2406, 'Havelländisches Luch', 'Havelländisches Luch', 24, '{BB,ST}'),
	(2407, 'Friesacker Platte', 'Friesacker Platte', 24, '{BB}'),
	(2408, 'Rhinluch', 'Rhinluch', 24, '{BB}'),
	(2409, 'Bellin-Glin-Platte', 'Bellin-Glin-Platte', 24, '{BB}'),
	(2410, 'Nauener Platte', 'Nauener Platte', 24, '{BE,BB}'),
	(2411, 'Brandenburger Niederung und Platten', 'Brandenburger Niederung und Platten', 24, '{BB}'),
	(2412, 'Potsdamer Seen und Hügel', 'Potsdamer Seen und Hügel', 24, '{BE,BB}'),
	(2413, 'Zauche Platte', 'Zauche Platte', 24, '{BB}'),
	(2414, 'Brücker Niederung', 'Brücker Niederung', 24, '{BB}'),
	(2415, 'Königs Wusterhausener Talsand und Platten', 'Königs Wusterhausener Talsand und Platten', 24, '{BE,BB}'),
	(2416, 'Teltower Platte', 'Teltower Platte', 24, '{BE,BB}'),
	(2417, 'Berlin-Fürstenwalder Talsand', 'Berlin-Fürstenwalder Talsand', 24, '{BE,BB}'),
	(2418, 'Oderaue', 'Oderaue', 24, '{BB}'),
	(2419, 'Neisseaue', 'Neisseaue', 24, '{BB}'),
	(2420, 'Beeskower Platte', 'Beeskower Platte', 24, '{BB}'),
	(2421, 'Oberspreewaldniederung', 'Oberspreewaldniederung', 24, '{BB}'),
	(2422, 'Unterspreewaldniederung', 'Unterspreewaldniederung', 24, '{BB}'),
	(2423, 'Baruther Tal', 'Baruther Tal', 24, '{BB}'),
	(2424, 'Radelander Sandebene', 'Radelander Sandebene', 24, '{BB}'),
	(2425, 'Teupitzer Platten und Hügel', 'Teupitzer Platten und Hügel', 24, '{BB}'),
	(2501, 'Dübener Heidehochfläche', 'Dübener Heidehochfläche', 25, '{SN,ST}'),
	(2502, 'Dommitzscher Randplatte (Dommitzscher Heiderandplatte)', 'Dommitzscher Randplatte (Dommitzscher Heiderandplatte)', 25, '{SN,ST}'),
	(2503, 'Wildenhainer Niederung', 'Wildenhainer Niederung', 25, '{SN}'),
	(2504, 'Schildauer Heiderandplatte', 'Schildauer Heiderandplatte', 25, '{SN}'),
	(2505, 'Dahlener Heidehochfläche', 'Dahlener Heidehochfläche', 25, '{SN}'),
	(2506, 'Mühlberger Elbauenabschnitt', 'Mühlberger Elbauenabschnitt', 25, '{BB,SN}'),
	(2507, 'Elsterwerdaer Niederung', 'Elsterwerdaer Niederung', 25, '{BB,SN}'),
	(2508, 'Thiendorfer Randplatten und Hochflächen', 'Thiendorfer Randplatten und Hochflächen', 25, '{BB,SN}'),
	(2509, 'Ruhlander Niederung', 'Ruhlander Niederung', 25, '{BB,SN}'),
	(2510, 'Königswarthaer Niederung', 'Königswarthaer Niederung', 25, '{SN}'),
	(2511, 'Nieskyer Randplatte', 'Nieskyer Randplatte', 25, '{SN}'),
	(2512, 'Krebaer Niederung', 'Krebaer Niederung', 25, '{SN}'),
	(2513, 'Nochtener Dünengebiet', 'Nochtener Dünengebiet', 25, '{SN}'),
	(2514, 'Muskauer Faltenbogen', 'Muskauer Faltenbogen', 25, '{BB,SN}'),
	(2515, 'Jerischker Platte', 'Jerischker Platte', 25, '{BB,SN}'),
	(2516, 'Grausteiner Platte', 'Grausteiner Platte', 25, '{BB,SN}'),
	(2517, 'Westspremberger kippenreiche Platte', 'Westspremberger kippenreiche Platte', 25, '{BB,SN}'),
	(2518, 'Senftenberger kippenreiche Platte', 'Senftenberger kippenreiche Platte', 25, '{BB}'),
	(2519, 'Finsterwalder Platte', 'Finsterwalder Platte', 25, '{BB}'),
	(2520, 'Kirchhainer Becken', 'Kirchhainer Becken', 25, '{BB}'),
	(2521, 'Prissener Platte', 'Prissener Platte', 25, '{BB}'),
	(2522, 'Schliebener Becken', 'Schliebener Becken', 25, '{BB}'),
	(2523, 'Lausitzer Grenzwall', 'Lausitzer Grenzwall', 25, '{BB}'),
	(2524, 'Drehnaer Becken', 'Drehnaer Becken', 25, '{BB}'),
	(2525, 'Luger Becken', 'Luger Becken', 25, '{BB}'),
	(2526, 'Drebkauer Platte', 'Drebkauer Platte', 25, '{BB}'),
	(2527, 'Cottbuser Talsand', 'Cottbuser Talsand', 25, '{BB}'),
	(2528, 'Gosdaer Platte', 'Gosdaer Platte', 25, '{BB}'),
	(2529, 'Spremberger Spreetalabschnitt', 'Spremberger Spreetalabschnitt', 25, '{BB,SN}'),
	(2601, 'Nordwestlausitzer Hügelland', 'Nordwestlausitzer Hügelland', 26, '{SN}'),
	(2602, 'Westlausitzer Löss-Hügelland', 'Westlausitzer Löss-Hügelland', 26, '{SN}'),
	(2603, 'Westlausitzer Vorberge', 'Westlausitzer Vorberge', 26, '{SN}'),
	(2604, 'Lausitzer Gefilde', 'Lausitzer Gefilde', 26, '{SN}'),
	(2605, 'Ostlausitzer Vorberge', 'Ostlausitzer Vorberge', 26, '{SN}'),
	(2606, 'Ostlausitzer Löss-Hügelland und Becken', 'Ostlausitzer Löss-Hügelland und Becken', 26, '{SN}'),
	(2700, 'Zittauer Gebirge', 'Zittauer Gebirge', 27, '{SN}'),
	(2800, 'Oberlausitzer Bergland', 'Oberlausitzer Bergland', 28, '{SN}'),
	(2901, 'Untere Sächsische Schweiz', 'Untere Sächsische Schweiz', 29, '{SN}'),
	(2902, 'Obere Sächsische Schweiz', 'Obere Sächsische Schweiz', 29, '{SN}'),
	(3001, 'Grossenhainer Löss-Hügelland', 'Grossenhainer Löss-Hügelland', 30, '{SN}'),
	(3002, 'Moritzburg-Radeberger Hügelland', 'Moritzburg-Radeberger Hügelland', 30, '{SN}'),
	(3003, 'Lohmener Sandstein-Löss-Ebenheiten', 'Lohmener Sandstein-Löss-Ebenheiten', 30, '{SN}'),
	(3004, 'Dresdener Erzgebirgsvorland', 'Dresdener Erzgebirgsvorland', 30, '{SN}'),
	(3005, 'Dresdener Elbtalweitung', 'Dresdener Elbtalweitung', 30, '{SN}'),
	(3101, 'Altenburg-Zeitzer-Löss-Hügelland', 'Altenburg-Zeitzer-Löss-Hügelland', 31, '{SN,ST,TH}'),
	(3102, 'Bad Lausicker Löss-Hügelland', 'Bad Lausicker Löss-Hügelland', 31, '{SN,TH}'),
	(3103, 'Wurzen-Oschatzer Sandlöss-Platten und Hügelland', 'Wurzen-Oschatzer Sandlöss-Platten und Hügelland', 31, '{SN}'),
	(3104, 'Lommatzscher Löss-Hügelland', 'Lommatzscher Löss-Hügelland', 31, '{SN}'),
	(3105, 'Nördliches Mulde-Löss-Hügelland', 'Nördliches Mulde-Löss-Hügelland', 31, '{SN}'),
	(3106, 'Ronneburger Schieferplatten (Neufassung)', 'Ronneburger Schieferplatten (Neufassung)', 31, '{SN,TH}'),
	(3201, 'Leipziger Elster-Aue', 'Leipziger Elster-Aue', 32, '{SN}'),
	(3202, 'Delitzsch-Naunhofer-Sandlöss-Ebene', 'Delitzsch-Naunhofer-Sandlöss-Ebene', 32, '{SN,ST}'),
	(3203, 'Bornaer Bergbaugebiet', 'Bornaer Bergbaugebiet', 32, '{SN,ST,TH}'),
	(3301, 'Ohrdrufer Platten', 'Ohrdrufer Platten', 33, '{TH}'),
	(3302, 'Heydaer und Paulinzellaer Buntsandstein', 'Heydaer und Paulinzellaer Buntsandstein', 33, '{TH}'),
	(3303, 'Ilm-Saale-Platten', 'Ilm-Saale-Platten', 33, '{ST,TH}'),
	(3304, 'Ostthüringischer Buntsandstein', 'Ostthüringischer Buntsandstein', 33, '{ST,TH}'),
	(3305, 'Orla-Senke', 'Orla-Senke', 33, '{TH}'),
	(3401, 'Westlicher Beckenrand', 'Westlicher Beckenrand', 34, '{TH}'),
	(3402, 'Gera-Unstrut-Niederung', 'Gera-Unstrut-Niederung', 34, '{TH}'),
	(3403, 'Thüringer Keuper-Becken', 'Thüringer Keuper-Becken', 34, '{ST,TH}'),
	(3501, 'Südliches Harzvorland', 'Südliches Harzvorland', 35, '{NI,ST,TH}'),
	(3502, 'Nordthüringischer Buntsandstein', 'Nordthüringischer Buntsandstein', 35, '{TH}'),
	(3503, 'Hainleite', 'Hainleite', 35, '{TH}'),
	(3504, 'Helme-Unstrut-Niederung', 'Helme-Unstrut-Niederung', 35, '{ST,TH}'),
	(3505, 'Kyffhäuser', 'Kyffhäuser', 35, '{ST,TH}'),
	(3506, 'Südöstliches Harzvorland', 'Südöstliches Harzvorland', 35, '{ST}'),
	(3507, 'Ziegelrodaer Buntsandstein-Platte', 'Ziegelrodaer Buntsandstein-Platte', 35, '{ST,TH}'),
	(3508, 'Finne-Schrecke-Schmücke-Hügelland', 'Finne-Schrecke-Schmücke-Hügelland', 35, '{ST,TH}'),
	(3509, 'Unstrut-Saale-Muschelkalk-Platten', 'Unstrut-Saale-Muschelkalk-Platten', 35, '{ST,TH}'),
	(3601, 'Unterer und mittlerer Harzrand', 'Unterer und mittlerer Harzrand', 36, '{NI,ST,TH}'),
	(3602, 'Montaner Ober- u. Mittelharz', 'Montaner Ober- u. Mittelharz', 36, '{NI,ST,TH}'),
	(3603, 'Harzhochlagen (wurde mit 3604 zusammengelegt)', 'Harzhochlagen (wurde mit 3604 zusammengelegt)', 36, '{NI,ST}'),
	(3604, 'Hochharz', 'Hochharz', 36, '{NI,ST}'),
	(3605, 'Mittelharz', 'Mittelharz', 36, '{NI,ST,TH}'),
	(3606, 'Nördlicher Harzrand', 'Nördlicher Harzrand', 36, '{NI,ST}'),
	(3607, 'Mittleres Unterharz-Plateau', 'Mittleres Unterharz-Plateau', 36, '{NI,ST,TH}'),
	(3608, 'Südharz', 'Südharz', 36, '{ST,TH}'),
	(3609, 'östlicher Unterharz', 'östlicher Unterharz', 36, '{ST}'),
	(3610, 'Ostharzer Abdachung', 'Ostharzer Abdachung', 36, '{ST}'),
	(3701, 'Unterer Solling', 'Unterer Solling', 37, '{NI,NW,HE}'),
	(3702, 'Hoher Solling', 'Hoher Solling', 37, '{NI}'),
	(3703, 'Rheinhardswald', 'Rheinhardswald', 37, '{NI,NW,HE}'),
	(3704, 'Bramwald-Brackenberg', 'Bramwald-Brackenberg', 37, '{NI,HE}'),
	(3705, 'Solling-Vorland', 'Solling-Vorland', 37, '{NI,NW,HE}'),
	(3706, 'Leine-Ilme-Senke', 'Leine-Ilme-Senke', 37, '{NI,HE,TH}'),
	(3707, 'Göttinger Wald', 'Göttinger Wald', 37, '{NI,TH}'),
	(3708, 'Südwestliches Harzvorland', 'Südwestliches Harzvorland', 37, '{NI,TH}'),
	(3709, 'Eichsfeld', 'Eichsfeld', 37, '{NI,TH}'),
	(3710, 'Ohmgebirge und Bleicheröder Berge', 'Ohmgebirge und Bleicheröder Berge', 37, '{TH}'),
	(3711, 'Unteres Eichsfeld', 'Unteres Eichsfeld', 37, '{NI,TH}'),
	(3712, 'Ringgau und angrenzendes Werragebiet', 'Ringgau und angrenzendes Werragebiet', 37, '{NI,HE,TH}'),
	(3713, 'Kaufunger Wald', 'Kaufunger Wald', 37, '{NI,HE}'),
	(3714, 'Meissner und Vorland', 'Meissner und Vorland', 37, '{HE}'),
	(3715, 'Rotenburger und Melsunger Bergland', 'Rotenburger und Melsunger Bergland', 37, '{HE}'),
	(3716, 'Richelsdorfer Gebirge', 'Richelsdorfer Gebirge', 37, '{HE,TH}'),
	(3717, 'Schwalm-Bergland', 'Schwalm-Bergland', 37, '{HE}'),
	(3718, 'Knüllgebirge', 'Knüllgebirge', 37, '{HE}'),
	(3719, 'Sandsteingebiet um Hersfeld', 'Sandsteingebiet um Hersfeld', 37, '{HE}'),
	(3720, 'Seulingswald', 'Seulingswald', 37, '{HE,TH}'),
	(3721, 'Waltershäuser Vorberge', 'Waltershäuser Vorberge', 37, '{TH}'),
	(3722, 'Werra-Bergland', 'Werra-Bergland', 37, '{HE,TH}'),
	(3801, 'Marburger Lahn-Bergland', 'Marburger Lahn-Bergland', 38, '{HE}'),
	(3802, 'Burgwald', 'Burgwald', 38, '{HE}'),
	(3803, 'Amöneburg-Neustädter-Gebiet', 'Amöneburg-Neustädter-Gebiet', 38, '{HE}'),
	(3804, 'Niederhessische Senke', 'Niederhessische Senke', 38, '{NI,HE}'),
	(3805, 'Habichtswald', 'Habichtswald', 38, '{HE}'),
	(3806, 'Diemelplatten', 'Diemelplatten', 38, '{NW,HE}'),
	(3807, 'Waldeck-Wolfhagener Berg- und Hügelland', 'Waldeck-Wolfhagener Berg- und Hügelland', 38, '{NW,HE}'),
	(3808, 'Korbacher Kalkgebiet', 'Korbacher Kalkgebiet', 38, '{NW,HE}'),
	(3901, 'Kellerwald', 'Kellerwald', 39, '{HE}'),
	(3902, 'Wildunger Bergland', 'Wildunger Bergland', 39, '{HE}'),
	(3903, 'östlicher Rothaargebirgs-Ausläufer', 'östlicher Rothaargebirgs-Ausläufer', 39, '{NW,HE}'),
	(3904, 'Südlicher Rothaargebirgs-Ausläufer', 'Südlicher Rothaargebirgs-Ausläufer', 39, '{NW,HE}'),
	(3905, 'Westliches Lahn-Dill-Bergland', 'Westliches Lahn-Dill-Bergland', 39, '{HE}'),
	(3906, 'östliches Lahn-Dill-Bergland', 'östliches Lahn-Dill-Bergland', 39, '{HE}'),
	(4002, 'Nordsauerländer Oberland', 'Nordsauerländer Oberland', 40, '{NW}'),
	(4003, 'Märkisches Sauerland', 'Märkisches Sauerland', 40, '{NW}'),
	(4004, 'Innersauerländer Senken', 'Innersauerländer Senken', 40, '{NW}'),
	(4005, 'Südsauerländer Bergland', 'Südsauerländer Bergland', 40, '{NW,RP}'),
	(4006, 'Rothaargebirge / Hochsauerland', 'Rothaargebirge / Hochsauerland', 40, '{NW,HE}'),
	(4007, 'Siegerland', 'Siegerland', 40, '{NW,RP}'),
	(4101, 'Bergische Randschwelle', 'Bergische Randschwelle', 41, '{NW}'),
	(4102, 'Niederbergisches Hügelland', 'Niederbergisches Hügelland', 41, '{NW}'),
	(4103, 'Bergische Hochflächen', 'Bergische Hochflächen', 41, '{NW}'),
	(4104, 'Oberbergisches Land', 'Oberbergisches Land', 41, '{NW}'),
	(4105, 'Mittelsieg-Bergland', 'Mittelsieg-Bergland', 41, '{NW,RP}'),
	(4106, 'Siebengebirge', 'Siebengebirge', 41, '{NW}'),
	(4201, 'Niederrheinebene', 'Niederrheinebene', 42, '{NW}'),
	(4202, 'Niederrheinische Höhen', 'Niederrheinische Höhen', 42, '{NW}'),
	(4203, 'Niers', 'Niers', 42, '{NW}'),
	(4204, 'Schwalm-Nette-Platten', 'Schwalm-Nette-Platten', 42, '{NW}'),
	(4301, 'Jülich-Zülpicher Börden', 'Jülich-Zülpicher Börden', 43, '{NW,RP}'),
	(4302, 'Ville', 'Ville', 43, '{NW}'),
	(4303, 'Köln-Bonner Rheinebene', 'Köln-Bonner Rheinebene', 43, '{NW}'),
	(4304, 'Drachenfelser Ländchen', 'Drachenfelser Ländchen', 43, '{NW,RP}'),
	(4401, 'Vennvorland', 'Vennvorland', 44, '{NW}'),
	(4402, 'Hohes Venn', 'Hohes Venn', 44, '{NW}'),
	(4403, 'Rureifel', 'Rureifel', 44, '{NW}'),
	(4404, 'Westliche Hocheifel', 'Westliche Hocheifel', 44, '{NW,RP}'),
	(4405, 'Kalkeifel', 'Kalkeifel', 44, '{NW,RP}'),
	(4406, 'Islek und Ösling', 'Islek und Ösling', 44, '{RP}'),
	(4407, 'Kyllburger Waldeifel', 'Kyllburger Waldeifel', 44, '{RP}'),
	(4501, 'Ahreifel', 'Ahreifel', 45, '{NW,RP}'),
	(4502, 'östlicher Eifelrand', 'östlicher Eifelrand', 45, '{RP}'),
	(4503, 'östliche Hocheifel', 'östliche Hocheifel', 45, '{RP}'),
	(4504, 'Moseleifel', 'Moseleifel', 45, '{RP}'),
	(4601, 'Unteres Mittelrheingebiet', 'Unteres Mittelrheingebiet', 46, '{NW,RP}'),
	(4602, 'Mittelrheinisches Becken', 'Mittelrheinisches Becken', 46, '{RP}'),
	(4603, 'Oberes Mittelrheintal', 'Oberes Mittelrheintal', 46, '{HE,RP}'),
	(4701, 'Niederwesterwald', 'Niederwesterwald', 47, '{NW,HE,RP}'),
	(4702, 'Oberwesterwald', 'Oberwesterwald', 47, '{HE,RP}'),
	(4703, 'Hoher Westerwald', 'Hoher Westerwald', 47, '{NW,HE,RP}'),
	(4704, 'östliches Westerwald-Vorland', 'östliches Westerwald-Vorland', 47, '{HE}'),
	(4705, 'Nördliches Limburger Becken', 'Nördliches Limburger Becken', 47, '{HE}'),
	(4801, 'Westlicher Hinter-Taunus', 'Westlicher Hinter-Taunus', 48, '{HE,RP}'),
	(4802, 'Unteres Lahntal', 'Unteres Lahntal', 48, '{RP}'),
	(4803, 'Südliches Limburger Becken', 'Südliches Limburger Becken', 48, '{HE,RP}'),
	(4804, 'östlicher Hinter-Taunus', 'östlicher Hinter-Taunus', 48, '{HE}'),
	(4805, 'Hoch-Taunus', 'Hoch-Taunus', 48, '{HE,RP}'),
	(4806, 'Südlicher Taunus', 'Südlicher Taunus', 48, '{HE}'),
	(4901, 'Giessener Becken und Giessener Schwelle', 'Giessener Becken und Giessener Schwelle', 49, '{HE}'),
	(4902, 'Wetterau und angrenzendes Hügelland', 'Wetterau und angrenzendes Hügelland', 49, '{HE}'),
	(5001, 'Vorderer Vogelsberg', 'Vorderer Vogelsberg', 50, '{HE}'),
	(5002, 'Südwestlicher Vogelsberg', 'Südwestlicher Vogelsberg', 50, '{HE}'),
	(5003, 'Büdinger Wald', 'Büdinger Wald', 50, '{HE}'),
	(5004, 'Hochfläche des östlichen Vogelsberges', 'Hochfläche des östlichen Vogelsberges', 50, '{HE}'),
	(5005, 'Oberwald', 'Oberwald', 50, '{HE}'),
	(5006, 'Hochfläche des nördlichen Vogelsberges', 'Hochfläche des nördlichen Vogelsberges', 50, '{HE}'),
	(5007, 'östlicher Vogelsberg', 'östlicher Vogelsberg', 50, '{HE}'),
	(5008, 'Schlitzer Bergland', 'Schlitzer Bergland', 50, '{HE}'),
	(5009, 'Fulda-Haune-Bergland', 'Fulda-Haune-Bergland', 50, '{HE}'),
	(5101, 'Vorderrhöhn', 'Vorderrhöhn', 51, '{HE,TH}'),
	(5102, 'Fuldaer-Rhön-Vorland', 'Fuldaer-Rhön-Vorland', 51, '{HE}'),
	(5103, 'Hohe Rhön', 'Hohe Rhön', 51, '{HE,BY,TH}'),
	(5104, 'Südrhön', 'Südrhön', 51, '{HE,BY}'),
	(5105, 'Vorrhön', 'Vorrhön', 51, '{HE,BY}'),
	(5201, 'Westthüringischer Buntsandstein', 'Westthüringischer Buntsandstein', 52, '{TH}'),
	(5202, 'Stedtlinger Gebiet', 'Stedtlinger Gebiet', 52, '{BY,TH}'),
	(5203, 'Meininger Muschelkalk', 'Meininger Muschelkalk', 52, '{BY,TH}'),
	(5204, 'Südthüringischer Buntsandstein', 'Südthüringischer Buntsandstein', 52, '{TH}'),
	(5205, 'Bruchschollenland', 'Bruchschollenland', 52, '{BY,TH}'),
	(5206, 'Obermainhügelland', 'Obermainhügelland', 52, '{BY}'),
	(5301, 'Nordwestlicher Thüringer Wald', 'Nordwestlicher Thüringer Wald', 53, '{TH}'),
	(5302, 'Mittlerer Thüringer Wald', 'Mittlerer Thüringer Wald', 53, '{TH}'),
	(5303, 'Hohes Schiefergebirge', 'Hohes Schiefergebirge', 53, '{TH}'),
	(5304, 'Nordabdachung des Schiefergebirges', 'Nordabdachung des Schiefergebirges', 53, '{BY,TH}'),
	(5401, 'Ronneburger Schieferplatte (Altfassung)', 'Ronneburger Schieferplatte (Altfassung)', 54, '{SN,TH}'),
	(5402, 'Unteres Vogtland', 'Unteres Vogtland', 54, '{SN,TH}'),
	(5403, 'Oberes Vogtland', 'Oberes Vogtland', 54, '{BY,SN,TH}'),
	(5404, 'Westvogtländische Hochflächen', 'Westvogtländische Hochflächen', 54, '{SN,TH}'),
	(5405, 'Vogtländisches Erzgebirgsvorland', 'Vogtländisches Erzgebirgsvorland', 54, '{SN,TH}'),
	(5406, 'Bayrisches Vogtland', 'Bayrisches Vogtland', 54, '{BY,SN,TH}'),
	(5407, 'Brambacher Zipfel', 'Brambacher Zipfel', 54, '{SN}'),
	(5501, 'Ronneburger Schiefer-Platte', 'Ronneburger Schiefer-Platte', 55, '{SN,TH}'),
	(5502, 'Westliches Erzgebirgsbecken', 'Westliches Erzgebirgsbecken', 55, '{SN,TH}'),
	(5503, 'östliches Erzgebirgsbecken', 'östliches Erzgebirgsbecken', 55, '{SN}'),
	(5504, 'Rabensteiner Schiefer-Höhenzug', 'Rabensteiner Schiefer-Höhenzug', 55, '{SN}'),
	(5505, 'Südliches Mulde-Löss-Hügelland', 'Südliches Mulde-Löss-Hügelland', 55, '{SN}'),
	(5601, 'Nordwestabdachung des Erzgebirges', 'Nordwestabdachung des Erzgebirges', 56, '{SN}'),
	(5602, 'Westliches Oberes Erzgebirge', 'Westliches Oberes Erzgebirge', 56, '{SN}'),
	(5603, 'Mittleres Oberes Erzgebirge', 'Mittleres Oberes Erzgebirge', 56, '{SN}'),
	(5604, 'östliches Oberes Erzgebirge', 'östliches Oberes Erzgebirge', 56, '{SN}'),
	(5605, 'Obere Nordabdachung des Osterzgebirges', 'Obere Nordabdachung des Osterzgebirges', 56, '{SN}'),
	(5606, 'Obere Nordabdachung des Mittleren Erzgebirges', 'Obere Nordabdachung des Mittleren Erzgebirges', 56, '{SN}'),
	(5607, 'Untere Nordabdachung des Mittleren Erzgebirges', 'Untere Nordabdachung des Mittleren Erzgebirges', 56, '{SN}'),
	(5608, 'Untere Nordostabdachung des Osterzgebirges', 'Untere Nordostabdachung des Osterzgebirges', 56, '{SN}'),
	(5701, 'Frankenwald', 'Frankenwald', 57, '{BY,TH}'),
	(5702, 'Münchberger Sattel', 'Münchberger Sattel', 57, '{BY}'),
	(5703, 'Fichtelgebirge', 'Fichtelgebirge', 57, '{BY}'),
	(5704, 'Selb-Wunsiedler Bucht', 'Selb-Wunsiedler Bucht', 57, '{BY}'),
	(5705, 'Brand-Neusorger Becken', 'Brand-Neusorger Becken', 57, '{BY}'),
	(5706, 'Steinwald', 'Steinwald', 57, '{BY}'),
	(5801, 'Mitterteicher Basaltgebiet', 'Mitterteicher Basaltgebiet', 58, '{BY}'),
	(5802, 'Waldsassener Schiefergebiet und Wiesauer Senke', 'Waldsassener Schiefergebiet und Wiesauer Senke', 58, '{BY}'),
	(5803, 'Vorderer Oberpfälzer Wald', 'Vorderer Oberpfälzer Wald', 58, '{BY}'),
	(5804, 'Innerer Oberpfälzer Wald', 'Innerer Oberpfälzer Wald', 58, '{BY}'),
	(5805, 'Cham-Further Senke', 'Cham-Further Senke', 58, '{BY}'),
	(5900, 'Oberpfälzer Becken- und Hügelland', 'Oberpfälzer Becken- und Hügelland', 59, '{BY}'),
	(6001, 'Nördliche Frankenalb und Nördlicher Oberpfälzer Jura', 'Nördliche Frankenalb und Nördlicher Oberpfälzer Jura', 60, '{BY}'),
	(6002, 'Oberfränkisches Braunjuragebiet', 'Oberfränkisches Braunjuragebiet', 60, '{BY}'),
	(6003, 'Oberpfälzer Jurarand', 'Oberpfälzer Jurarand', 60, '{BY}'),
	(6004, 'Südliche Frankenalb und Südlicher Oberpfälzer Jura', 'Südliche Frankenalb und Südlicher Oberpfälzer Jura', 60, '{BY}'),
	(6005, 'Schwäbische Riesalb', 'Schwäbische Riesalb', 60, '{BW,BY}'),
	(6101, 'Itz-Baunach-Hügelland', 'Itz-Baunach-Hügelland', 61, '{BY,TH}'),
	(6102, 'Hassberge', 'Hassberge', 61, '{BY}'),
	(6103, 'Steigerwald', 'Steigerwald', 61, '{BY}'),
	(6104, 'Nördliche Keuperabdachung', 'Nördliche Keuperabdachung', 61, '{BY}'),
	(6105, 'Nördliches Albvorland', 'Nördliches Albvorland', 61, '{BY}'),
	(6106, 'Südliches Albvorland', 'Südliches Albvorland', 61, '{BY}'),
	(6107, 'Südliche Keuperabdachung', 'Südliche Keuperabdachung', 61, '{BW,BY}'),
	(6108, 'Frankenhöhe', 'Frankenhöhe', 61, '{BW,BY}'),
	(6109, 'Ries', 'Ries', 61, '{BW,BY}'),
	(6201, 'Nördliche Fränkische Platte', 'Nördliche Fränkische Platte', 62, '{BY,TH}'),
	(6202, 'Südliche Fränkische Platte', 'Südliche Fränkische Platte', 62, '{BW,BY}'),
	(6301, 'Grundgebirgsspessart', 'Grundgebirgsspessart', 63, '{HE,BY}'),
	(6302, 'Buntsandsteinspessart', 'Buntsandsteinspessart', 63, '{HE,BW,BY}'),
	(6303, 'Nordwestlicher Spessart', 'Nordwestlicher Spessart', 63, '{HE,BY}'),
	(6304, 'Zentraler Hessischer Spessart', 'Zentraler Hessischer Spessart', 63, '{HE,BY}'),
	(6305, 'Hessischer Sinn-Talbereich', 'Hessischer Sinn-Talbereich', 63, '{HE,BY}'),
	(6306, 'Oberes Kinzig-Gebiet', 'Oberes Kinzig-Gebiet', 63, '{HE}'),
	(6401, 'Nordwestlicher Odenwald', 'Nordwestlicher Odenwald', 64, '{HE}'),
	(6402, 'Höhere Lage des kristallinen Odenwaldes', 'Höhere Lage des kristallinen Odenwaldes', 64, '{HE,BW}'),
	(6403, 'Bergstrasse', 'Bergstrasse', 64, '{HE,BW}'),
	(6404, 'Grundgebirgs-Odenwald', 'Grundgebirgs-Odenwald', 64, '{HE,BW}'),
	(6405, 'Westlicher Kleiner Odenwald', 'Westlicher Kleiner Odenwald', 64, '{BW}'),
	(6406, 'Kleiner Odenwald', 'Kleiner Odenwald', 64, '{HE,BW}'),
	(6407, 'Südwestlicher Buntsandstein-Odenwald', 'Südwestlicher Buntsandstein-Odenwald', 64, '{HE,BW,BY}'),
	(6408, 'Nördlicher Sandstein-Odenwald', 'Nördlicher Sandstein-Odenwald', 64, '{HE,BY}'),
	(6409, 'Bayrischer Odenwald', 'Bayrischer Odenwald', 64, '{HE,BW,BY}'),
	(6410, 'Winterhauch', 'Winterhauch', 64, '{HE,BW}'),
	(6411, 'Odenwaldrand zwischen Neckar und Main', 'Odenwaldrand zwischen Neckar und Main', 64, '{BW,BY}'),
	(6412, 'Schattseitige Taubertaleinhänge', 'Schattseitige Taubertaleinhänge', 64, '{BW,BY}'),
	(6501, 'Unteres Naheland', 'Unteres Naheland', 65, '{RP}'),
	(6502, 'Rheinhessisches Tafel- und Hügelland', 'Rheinhessisches Tafel- und Hügelland', 65, '{RP}'),
	(6503, 'Hessische Rheinniederung', 'Hessische Rheinniederung', 65, '{HE,RP,BW}'),
	(6504, 'Main-Taunus-Vorland', 'Main-Taunus-Vorland', 65, '{HE,RP}'),
	(6505, 'Hanau-Seligenstädter Senke', 'Hanau-Seligenstädter Senke', 65, '{HE,BY}'),
	(6506, 'Untermainebene', 'Untermainebene', 65, '{HE,RP,BY}'),
	(6507, 'Nördliches Odenwald-Vorland', 'Nördliches Odenwald-Vorland', 65, '{HE,BY}'),
	(6508, 'Hessische Rheinebene', 'Hessische Rheinebene', 65, '{HE,BW}'),
	(6509, 'Hardtwaldungen', 'Hardtwaldungen', 65, '{HE,RP,BW}'),
	(6510, 'Badisch-Pfälzische Rheinauen', 'Badisch-Pfälzische Rheinauen', 65, '{HE,RP,BW}'),
	(6511, 'Pfälzische Rheinebene', 'Pfälzische Rheinebene', 65, '{RP}'),
	(6512, 'Weinstrasse', 'Weinstrasse', 65, '{RP}'),
	(6513, 'Staubereich der ehemaligen Rheinaue', 'Staubereich der ehemaligen Rheinaue', 65, '{BW}'),
	(6514, 'Rheinebene von Rastatt bis Breisach', 'Rheinebene von Rastatt bis Breisach', 65, '{BW}'),
	(6515, 'Rheinhügelland zwischen Baden-Baden und Emmendingen', 'Rheinhügelland zwischen Baden-Baden und Emmendingen', 65, '{BW}'),
	(6516, 'Freiburger Bucht', 'Freiburger Bucht', 65, '{BW}'),
	(6517, 'Markgräflerland', 'Markgräflerland', 65, '{BW}'),
	(6518, 'Kaiserstuhl', 'Kaiserstuhl', 65, '{BW}'),
	(6519, 'Ehemaliger Ostrhein', 'Ehemaliger Ostrhein', 65, '{BW}'),
	(6520, 'Rheinebene von Breisach bis Basel', 'Rheinebene von Breisach bis Basel', 65, '{BW}'),
	(6521, 'Trockengebiet im Bereich der ehemaligen Rheinaue', 'Trockengebiet im Bereich der ehemaligen Rheinaue', 65, '{BW}'),
	(6522, 'Dinkelberg', 'Dinkelberg', 65, '{BW}'),
	(6523, 'Kinzig-Murg-Rinne', 'Kinzig-Murg-Rinne', 65, '{BW}'),
	(6601, 'Rhein-Hunsrück', 'Rhein-Hunsrück', 66, '{RP}'),
	(6602, 'Mosel-Hunsrück', 'Mosel-Hunsrück', 66, '{RP}'),
	(6603, 'östliche Hunsrück-Hochfläche', 'östliche Hunsrück-Hochfläche', 66, '{RP}'),
	(6604, 'Simmerner Mulde', 'Simmerner Mulde', 66, '{RP}'),
	(6605, 'Soonwald', 'Soonwald', 66, '{RP}'),
	(6606, 'Hoch- u. Idarwald', 'Hoch- u. Idarwald', 66, '{RP,SL}'),
	(6607, 'Westliche Hunsrück-Hochfläche', 'Westliche Hunsrück-Hochfläche', 66, '{RP}'),
	(6608, 'Saar-Ruwer-Hunsrück', 'Saar-Ruwer-Hunsrück', 66, '{RP,SL}'),
	(6701, 'Wittlicher Senke', 'Wittlicher Senke', 67, '{RP}'),
	(6702, 'Mittleres Moseltal', 'Mittleres Moseltal', 67, '{RP}'),
	(6703, 'Unteres Saartal', 'Unteres Saartal', 67, '{RP}'),
	(6801, 'Bitburger Gutland', 'Bitburger Gutland', 68, '{RP}'),
	(6802, 'Ferschweiler Plateau', 'Ferschweiler Plateau', 68, '{RP}'),
	(6803, 'Mosel-Saar-Gau', 'Mosel-Saar-Gau', 68, '{RP,SL}'),
	(6901, 'Gaulandschaften', 'Gaulandschaften', 69, '{SL}'),
	(6902, 'Bliesgau', 'Bliesgau', 69, '{RP,SL}'),
	(6903, 'Westricher Hochfläche', 'Westricher Hochfläche', 69, '{RP,SL}'),
	(7001, 'Saarbecken und Buntsandsteinbereich', 'Saarbecken und Buntsandsteinbereich', 70, '{RP,SL}'),
	(7002, 'Saarbergland', 'Saarbergland', 70, '{SL}'),
	(7003, 'Saarkohlenwald', 'Saarkohlenwald', 70, '{SL}'),
	(7004, 'Prims-Nahe-Bergland', 'Prims-Nahe-Bergland', 70, '{RP,SL}'),
	(7005, 'Westricher Bergland', 'Westricher Bergland', 70, '{RP,SL}'),
	(7006, 'Soonwaldvorstufe', 'Soonwaldvorstufe', 70, '{RP}'),
	(7007, 'Nordpfälzer Bergland', 'Nordpfälzer Bergland', 70, '{RP}'),
	(7100, 'Westricher Moorniederung', 'Westricher Moorniederung', 71, '{RP,SL}'),
	(7201, 'Nördlicher Pfälzerwald', 'Nördlicher Pfälzerwald', 72, '{RP}'),
	(7202, 'Mittlerer Pfälzerwald', 'Mittlerer Pfälzerwald', 72, '{RP}'),
	(7203, 'Wasgau (Südlicher Pfälzerwald)', 'Wasgau (Südlicher Pfälzerwald)', 72, '{RP}'),
	(7204, 'Haardt', 'Haardt', 72, '{RP}'),
	(7301, 'Nördliches Schwarzwaldvorland', 'Nördliches Schwarzwaldvorland', 73, '{BW}'),
	(7302, 'Hagenschiess', 'Hagenschiess', 73, '{BW}'),
	(7303, 'Schwarzwaldrand bei Neuenbürg', 'Schwarzwaldrand bei Neuenbürg', 73, '{BW}'),
	(7304, 'Vorgebirg zwischen Murg und Elz', 'Vorgebirg zwischen Murg und Elz', 73, '{BW}'),
	(7305, 'Hornisgrinde-Murgschwarzwald', 'Hornisgrinde-Murgschwarzwald', 73, '{BW}'),
	(7306, 'Enzhöhen', 'Enzhöhen', 73, '{BW}'),
	(7307, 'Flächenschwarzwald', 'Flächenschwarzwald', 73, '{BW}'),
	(7308, 'Ostrand des Flächenschwarzwaldes', 'Ostrand des Flächenschwarzwaldes', 73, '{BW}'),
	(7309, 'Schwarzwaldrand bei Winzeln', 'Schwarzwaldrand bei Winzeln', 73, '{BW}'),
	(7310, 'Mittlerer Schwarzwald zwischen Kinzig und Schwarzwaldhochstrasse', 'Mittlerer Schwarzwald zwischen Kinzig und Schwarzwaldhochstrasse', 73, '{BW}'),
	(7311, 'Mittlerer Schwarzwald zwischen Kinzig und Dreisam', 'Mittlerer Schwarzwald zwischen Kinzig und Dreisam', 73, '{BW}'),
	(7312, 'Südöstlicher Mittlerer Schwarzwald', 'Südöstlicher Mittlerer Schwarzwald', 73, '{BW}'),
	(7313, 'östlicher Südschwarzwald', 'östlicher Südschwarzwald', 73, '{BW}'),
	(7314, 'Hotzenwald', 'Hotzenwald', 73, '{BW}'),
	(7315, 'Schopfheimer Bergland', 'Schopfheimer Bergland', 73, '{BW}'),
	(7316, 'Westlicher Südschwarzwald', 'Westlicher Südschwarzwald', 73, '{BW}'),
	(7401, 'Baar-Schwarzwald', 'Baar-Schwarzwald', 74, '{BW}'),
	(7402, 'Baar', 'Baar', 74, '{BW}'),
	(7403, 'Obere Wutach und Bonndorfer Platte', 'Obere Wutach und Bonndorfer Platte', 74, '{BW}'),
	(7404, 'Untere Wutach und südöstlicher Hotzenwald', 'Untere Wutach und südöstlicher Hotzenwald', 74, '{BW}'),
	(7501, 'Vorderes Bauland', 'Vorderes Bauland', 75, '{BW}'),
	(7502, 'Hinteres Bauland', 'Hinteres Bauland', 75, '{BW}'),
	(7503, 'Langenbrücker Senke', 'Langenbrücker Senke', 75, '{BW}'),
	(7504, 'Kraichgau', 'Kraichgau', 75, '{BW}'),
	(7505, 'Kocher-Jagstlandschaft und Südrand des Baulandes', 'Kocher-Jagstlandschaft und Südrand des Baulandes', 75, '{BW}'),
	(7506, 'Hohenloher Ebene', 'Hohenloher Ebene', 75, '{BW,BY}'),
	(7507, 'Pfinzgau', 'Pfinzgau', 75, '{BW}'),
	(7508, 'Weinbaugebiet von Stuttgart, Maulbronn, Heilbronn', 'Weinbaugebiet von Stuttgart, Maulbronn, Heilbronn', 75, '{BW}'),
	(7509, 'Stromberg', 'Stromberg', 75, '{BW}'),
	(7510, 'Löwensteiner und Waldenburger Berge mit Nordteil der Limpurger Berge', 'Löwensteiner und Waldenburger Berge mit Nordteil der Limpurger Berge', 75, '{BW}'),
	(7511, 'Backnanger Bucht', 'Backnanger Bucht', 75, '{BW}'),
	(7512, 'Innerer Schwäbisch-Fränkischer Wald', 'Innerer Schwäbisch-Fränkischer Wald', 75, '{BW}'),
	(7513, 'Burgberg und nordwestlicher Virngrund', 'Burgberg und nordwestlicher Virngrund', 75, '{BW}'),
	(7514, 'Virngrund', 'Virngrund', 75, '{BW,BY}'),
	(7515, 'Vorland der Ostalb', 'Vorland der Ostalb', 75, '{BW}'),
	(7516, 'Bergland bei Schwäbisch Gmünd', 'Bergland bei Schwäbisch Gmünd', 75, '{BW}'),
	(7517, 'Berglen und Vorderer Schurwald', 'Berglen und Vorderer Schurwald', 75, '{BW}'),
	(7518, 'Nürtinger Bucht', 'Nürtinger Bucht', 75, '{BW}'),
	(7519, 'Vorland der Mittleren Alb', 'Vorland der Mittleren Alb', 75, '{BW}'),
	(7520, 'Schönbuch und Rammert', 'Schönbuch und Rammert', 75, '{BW}'),
	(7521, 'Oberes Gäu und Heckengäu', 'Oberes Gäu und Heckengäu', 75, '{BW}'),
	(7522, 'Oberer Neckar', 'Oberer Neckar', 75, '{BW}'),
	(7523, 'Albvorland südwestlich der Eyach', 'Albvorland südwestlich der Eyach', 75, '{BW}'),
	(7524, 'Albvorland östlich der Eyach', 'Albvorland östlich der Eyach', 75, '{BW}'),
	(7601, 'Nördliche Ostalb', 'Nördliche Ostalb', 76, '{BW}'),
	(7602, 'Mittlere Ostalb', 'Mittlere Ostalb', 76, '{BW,BY}'),
	(7603, 'Traufzone der Mittleren Alb', 'Traufzone der Mittleren Alb', 76, '{BW}'),
	(7604, 'Nordteil der Mittleren Alb', 'Nordteil der Mittleren Alb', 76, '{BW}'),
	(7605, 'Mittlere Donaualb', 'Mittlere Donaualb', 76, '{BW,BY}'),
	(7606, 'Traufzone der Zollern- und Heubergalb', 'Traufzone der Zollern- und Heubergalb', 76, '{BW}'),
	(7607, 'Zollern- und Heubergalb', 'Zollern- und Heubergalb', 76, '{BW}'),
	(7608, 'Südwestliche Donaualb', 'Südwestliche Donaualb', 76, '{BW}'),
	(7609, 'Baaralb und Randen', 'Baaralb und Randen', 76, '{BW}'),
	(7610, 'Hegaualb', 'Hegaualb', 76, '{BW}'),
	(7611, 'Südliche Baaralb-Randen', 'Südliche Baaralb-Randen', 76, '{BW}'),
	(7701, 'Nördliches Oberschwaben', 'Nördliches Oberschwaben', 77, '{BW,BY}'),
	(7702, 'Westliche Altmoräne', 'Westliche Altmoräne', 77, '{BW}'),
	(7703, 'Weissjura-Moräne bei Engen', 'Weissjura-Moräne bei Engen', 77, '{BW}'),
	(7704, 'Hegaubergland', 'Hegaubergland', 77, '{BW}'),
	(7705, 'Westliches Bodenseegebiet', 'Westliches Bodenseegebiet', 77, '{BW}'),
	(7706, 'Klettgau', 'Klettgau', 77, '{BW}'),
	(7707, 'Hegauniederung', 'Hegauniederung', 77, '{BW}'),
	(7708, 'Südwestliches Oberschwaben', 'Südwestliches Oberschwaben', 77, '{BW,BY}'),
	(7709, 'Würmmoräne von Altshausen-Waldsee', 'Würmmoräne von Altshausen-Waldsee', 77, '{BW}'),
	(7710, 'Hochgeländ und Rissmoräne von Bellamont', 'Hochgeländ und Rissmoräne von Bellamont', 77, '{BW}'),
	(7711, 'Rissmoräne und Schotterlandschaft von Wurzach-Zeil', 'Rissmoräne und Schotterlandschaft von Wurzach-Zeil', 77, '{BW,BY}'),
	(7712, 'Westallgäuer Hügelland', 'Westallgäuer Hügelland', 77, '{BW,BY}'),
	(7713, 'Drumlinlandschaft am Mittellauf der Argen', 'Drumlinlandschaft am Mittellauf der Argen', 77, '{BW,BY}'),
	(7714, 'Bodensee- und Schussenbecken', 'Bodensee- und Schussenbecken', 77, '{BW,BY}'),
	(7801, 'Donauried', 'Donauried', 78, '{BW,BY}'),
	(7802, 'Mittelschwäbisches Schotterriedel- und Hügelland', 'Mittelschwäbisches Schotterriedel- und Hügelland', 78, '{BW,BY}'),
	(7803, 'Unteres Lechtal', 'Unteres Lechtal', 78, '{BY}'),
	(7804, 'Ingolstädter Donauniederung', 'Ingolstädter Donauniederung', 78, '{BY}'),
	(7805, 'Oberbayerisches Tertiärhügelland', 'Oberbayerisches Tertiärhügelland', 78, '{BW,BY}'),
	(7806, 'Niederbayerisches Tertiärhügelland', 'Niederbayerisches Tertiärhügelland', 78, '{BY}'),
	(7807, 'Unteres Isartal', 'Unteres Isartal', 78, '{BY}'),
	(7808, 'Ostbayerische Donauniederung', 'Ostbayerische Donauniederung', 78, '{BY}'),
	(7809, 'Unteres Inntal', 'Unteres Inntal', 78, '{BY}'),
	(7901, 'Westlicher Vorderer Bayerischer Wald', 'Westlicher Vorderer Bayerischer Wald', 79, '{BY}'),
	(7902, 'östlicher Vorderer Bayerischer Wald', 'östlicher Vorderer Bayerischer Wald', 79, '{BY}'),
	(7903, 'Innerer Bayerischer Wald', 'Innerer Bayerischer Wald', 79, '{BY}'),
	(8001, 'Vorallgäu', 'Vorallgäu', 80, '{BW,BY}'),
	(8002, 'Lechfeld', 'Lechfeld', 80, '{BY}'),
	(8003, 'Landsberger Altmoräne', 'Landsberger Altmoräne', 80, '{BY}'),
	(8004, 'Münchener Schotterebene', 'Münchener Schotterebene', 80, '{BY}'),
	(8005, 'Isener Altmoräne und Hochterrasse', 'Isener Altmoräne und Hochterrasse', 80, '{BY}'),
	(8006, 'Mühldorfer u. Öttinger Schotterfelder', 'Mühldorfer u. Öttinger Schotterfelder', 80, '{BY}'),
	(8007, 'Trostberger Altmoräne und Hochterrasse', 'Trostberger Altmoräne und Hochterrasse', 80, '{BY}'),
	(8101, 'Bayerische Bodenseelandschaft', 'Bayerische Bodenseelandschaft', 81, '{BW,BY}'),
	(8102, 'Westallgäuer Bergland', 'Westallgäuer Bergland', 81, '{BW,BY}'),
	(8103, 'Schwäbische Jungmoräne und Molassevorberge', 'Schwäbische Jungmoräne und Molassevorberge', 81, '{BY}'),
	(8104, 'Oberbayerische Jungmoräne und Molassevorberge', 'Oberbayerische Jungmoräne und Molassevorberge', 81, '{BY}'),
	(8201, 'Kürnacher Molassebergland', 'Kürnacher Molassebergland', 82, '{BW,BY}'),
	(8202, 'Allgäuer Molassevoralpen', 'Allgäuer Molassevoralpen', 82, '{BY}'),
	(8203, 'Allgäuer Flysch-u. Helvetikumvoralpen', 'Allgäuer Flysch-u. Helvetikumvoralpen', 82, '{BY}'),
	(8204, 'Allgäuer Hochalpen', 'Allgäuer Hochalpen', 82, '{BY}'),
	(8205, 'Oberbayerische Flysch-Voralpen', 'Oberbayerische Flysch-Voralpen', 82, '{BY}'),
	(8206, 'Mittlere Bayerische Kalkalpen', 'Mittlere Bayerische Kalkalpen', 82, '{BY}'),
	(8207, 'Karwendel und Wettersteinmassiv', 'Karwendel und Wettersteinmassiv', 82, '{BY}'),
	(8208, 'Chiemgauer Alpen und Saalforstamt Unken', 'Chiemgauer Alpen und Saalforstamt Unken', 82, '{BY}'),
	(8209, 'Berchtesgadener Hochalpen und Saalforstämter (St. Martin und Leogang)', 'Berchtesgadener Hochalpen und Saalforstämter (St. Martin und Leogang)', 82, '{BY}');

