SET search_path TO private_ci2027_001;

--
-- TOC entry 286 (class 1259 OID 19089)
-- Name: lookup_growth_area; Type: TABLE; Schema: private_ci2027_001; Owner: postgres
--
CREATE TABLE lookup_growth_area AS TABLE lookup_TEMPLATE WITH NO DATA;
ALTER TABLE lookup_growth_area ADD COLUMN abbreviation integer UNIQUE NOT NULL;
ALTER TABLE lookup_growth_area ADD COLUMN states enum_state[];


ALTER TABLE lookup_growth_area OWNER TO postgres;


INSERT INTO lookup_growth_area (abbreviation, name_de, name_en, states) VALUES
	(1, 'Schleswig-Holstein Nordwest', 'Schleswig-Holstein Nordwest', '{SH}'),
	(3, 'Schleswig-Holstein Südwest', 'Schleswig-Holstein Südwest', '{SH,HH,NI}'),
	(2, 'Jungmoränenlandschaft Schleswig-Holstein Ost / Nordwest-Mecklenburg', 'Jungmoränenlandschaft Schleswig-Holstein Ost / Nordwest-Mecklenburg', '{SH,HH,NI,MV}'),
	(4, 'Mecklenburg-Westvorpommersches Küstenland', 'Mecklenburg-Westvorpommersches Küstenland', '{MV}'),
	(5, 'Ostholsteinisch-Westmecklenburger Jungmoränenland', 'Ostholsteinisch-Westmecklenburger Jungmoränenland', '{BB,MV}'),
	(6, '(Mittel-) Mecklenburger Jungmoränenland', '(Mittel-) Mecklenburger Jungmoränenland', '{BB,MV}'),
	(7, 'Ostmecklenburg-Vorpommersches Jungmoränenland', 'Ostmecklenburg-Vorpommersches Jungmoränenland', '{BB,MV}'),
	(8, 'Ostvorpommersches Küstenland', 'Ostvorpommersches Küstenland', '{MV}'),
	(9, 'Nordostbrandenburger Jungmoränenland (Mittelbrandenburger Jungmoränenland)', 'Nordostbrandenburger Jungmoränenland (Mittelbrandenburger Jungmoränenland)', '{BE,BB,MV}'),
	(10, 'Ostmecklenburg-Nordbrandenburger Jungmoränenland (Nordbrandenburger Jungmoränenland)', 'Ostmecklenburg-Nordbrandenburger Jungmoränenland (Nordbrandenburger Jungmoränenland)', '{BB,MV}'),
	(11, 'Ostniedersächsisch-altmärkisches Altmoränenland (Westprignitz-Altmärkisches Altmoränenland)', 'Ostniedersächsisch-altmärkisches Altmoränenland (Westprignitz-Altmärkisches Altmoränenland)', '{NI,BB,MV,ST}'),
	(12, 'Südost-Holsteinisch-Südwestmecklenburger Altmoränenland', 'Südost-Holsteinisch-Südwestmecklenburger Altmoränenland', '{SH,NI,BB,MV}'),
	(13, 'Ostniedersächsisches Tiefland', 'Ostniedersächsisches Tiefland', '{SH,HH,NI,BB,MV,ST}'),
	(14, 'Niedersächsischer Küstenraum', 'Niedersächsischer Küstenraum', '{HH,NI,HB}'),
	(15, 'Mittelwestniedersächsisches Tiefland', 'Mittelwestniedersächsisches Tiefland', '{NI,HB,NW}'),
	(16, 'Westfälische Bucht', 'Westfälische Bucht', '{NI,NW}'),
	(17, 'Weserbergland', 'Weserbergland', '{NI,NW,HE}'),
	(18, 'Nordwestdeutsche Berglandschwelle', 'Nordwestdeutsche Berglandschwelle', '{NI,NW,ST}'),
	(19, 'Nordwestliches Harzvorland', 'Nordwestliches Harzvorland', '{NI,ST}'),
	(20, 'Nordöstliche Harzvorländer', 'Nordöstliche Harzvorländer', '{ST}'),
	(21, 'Sachsen-Anhaltinische Löss-Ebene', 'Sachsen-Anhaltinische Löss-Ebene', '{SN,ST}'),
	(22, 'Mittleres nordostdeutsches Altmoränenland', 'Mittleres nordostdeutsches Altmoränenland', '{BB,SN,ST}'),
	(23, 'Hoher Fläming', 'Hoher Fläming', '{BB,ST}'),
	(24, 'Mittelbrandenburger Talsand- und Moränenland', 'Mittelbrandenburger Talsand- und Moränenland', '{BE,BB,SN,ST}'),
	(25, 'Düben-Niederlausitzer Altmoränenland', 'Düben-Niederlausitzer Altmoränenland', '{BB,SN,ST}'),
	(26, 'Lausitzer Löss-Hügelland', 'Lausitzer Löss-Hügelland', '{SN}'),
	(27, 'Zittauer Gebirge', 'Zittauer Gebirge', '{SN}'),
	(28, 'Oberlausitzer Bergland', 'Oberlausitzer Bergland', '{SN}'),
	(29, 'Elbsandsteingebirge', 'Elbsandsteingebirge', '{SN}'),
	(30, 'Westlausitzer Platte und Elbtalzone', 'Westlausitzer Platte und Elbtalzone', '{SN}'),
	(31, 'Sächsisch-Thüringisches Löss-Hügelland', 'Sächsisch-Thüringisches Löss-Hügelland', '{SN,ST,TH}'),
	(32, 'Leipziger Sandlöss-Ebene', 'Leipziger Sandlöss-Ebene', '{SN,ST,TH}'),
	(33, 'Ostthüringisches Trias-Hügelland', 'Ostthüringisches Trias-Hügelland', '{ST,TH}'),
	(34, 'Thüringer Becken', 'Thüringer Becken', '{ST,TH}'),
	(35, 'Nordthüringisches Trias-Hügelland', 'Nordthüringisches Trias-Hügelland', '{NI,ST,TH}'),
	(36, 'Harz', 'Harz', '{NI,ST,TH}'),
	(37, 'Mitteldeutsches Trias-Berg- und Hügelland', 'Mitteldeutsches Trias-Berg- und Hügelland', '{NI,NW,HE,TH}'),
	(38, 'Nordwesthessisches Bergland', 'Nordwesthessisches Bergland', '{NI,NW,HE}'),
	(39, 'Nördliches hessisches Schiefergebirge', 'Nördliches hessisches Schiefergebirge', '{NW,HE}'),
	(40, 'Sauerland', 'Sauerland', '{NW,HE,RP}'),
	(41, 'Bergisches Land', 'Bergisches Land', '{NW,RP}'),
	(42, 'Niederrheinisches Tiefland', 'Niederrheinisches Tiefland', '{NW}'),
	(43, 'Niederrheinische Bucht', 'Niederrheinische Bucht', '{NW,RP}'),
	(44, 'Nordwesteifel', 'Nordwesteifel', '{NW,RP}'),
	(45, 'Osteifel', 'Osteifel', '{NW,RP}'),
	(46, 'Mittelrheintal', 'Mittelrheintal', '{HE,RP}'),
	(47, 'Westerwald', 'Westerwald', '{NW,HE,RP}'),
	(48, 'Taunus', 'Taunus', '{HE,RP}'),
	(49, 'Wetterau und Giessener Becken', 'Wetterau und Giessener Becken', '{HE}'),
	(50, 'Vogelsberg und östlich angrenzende Sandsteingebiete', 'Vogelsberg und östlich angrenzende Sandsteingebiete', '{HE}'),
	(51, 'Rhön', 'Rhön', '{HE,BY,TH}'),
	(52, 'Südthüringisches-Oberfränkisches Trias-Hügelland', 'Südthüringisches-Oberfränkisches Trias-Hügelland', '{BY,TH}'),
	(53, 'Thüringer Gebirge', 'Thüringer Gebirge', '{BY,TH}'),
	(54, 'Vogtland', 'Vogtland', '{BY,SN,TH}'),
	(55, 'Erzgebirgsvorland', 'Erzgebirgsvorland', '{SN,TH}'),
	(56, 'Erzgebirge', 'Erzgebirge', '{SN}'),
	(57, 'Frankenwald, Fichtelgebirge und Steinwald', 'Frankenwald, Fichtelgebirge und Steinwald', '{BY,TH}'),
	(58, 'Oberpfälzer Wald', 'Oberpfälzer Wald', '{BY}'),
	(59, 'Oberpfälzer Becken- und Hügelland', 'Oberpfälzer Becken- und Hügelland', '{BY}'),
	(60, 'Frankenalb und Oberpfälzer Jura', 'Frankenalb und Oberpfälzer Jura', '{BW,BY}'),
	(61, 'Fränkischer Keuper und Albvorland', 'Fränkischer Keuper und Albvorland', '{BW,BY,TH}'),
	(62, 'Fränkische Platte', 'Fränkische Platte', '{BW,BY,TH}'),
	(63, 'Spessart', 'Spessart', '{HE,BW,BY}'),
	(64, 'Odenwald', 'Odenwald', '{HE,BW,BY}'),
	(65, 'Oberrheinisches Tiefland und Rhein-Main-Ebene', 'Oberrheinisches Tiefland und Rhein-Main-Ebene', '{HE,RP,BW,BY}'),
	(66, 'Hunsrück', 'Hunsrück', '{RP,SL}'),
	(67, 'Moseltal', 'Moseltal', '{RP}'),
	(68, 'Gutland', 'Gutland', '{RP,SL}'),
	(69, 'Saarländisch-Pfälzisches Muschelkalkgebiet', 'Saarländisch-Pfälzisches Muschelkalkgebiet', '{RP,SL}'),
	(70, 'Saar-Nahe Bergland', 'Saar-Nahe Bergland', '{RP,SL}'),
	(71, 'Westricher Moorniederung', 'Westricher Moorniederung', '{RP,SL}'),
	(72, 'Pfälzerwald', 'Pfälzerwald', '{RP}'),
	(73, 'Schwarzwald', 'Schwarzwald', '{BW}'),
	(74, 'Baar-Wutach', 'Baar-Wutach', '{BW}'),
	(75, 'Neckarland', 'Neckarland', '{BW,BY}'),
	(76, 'Schwäbische Alb', 'Schwäbische Alb', '{BW,BY}'),
	(77, 'Südwestdeutsches Alpenvorland', 'Südwestdeutsches Alpenvorland', '{BW,BY}'),
	(78, 'Tertiäres Hügelland', 'Tertiäres Hügelland', '{BW,BY}'),
	(79, 'Bayerischer Wald', 'Bayerischer Wald', '{BY}'),
	(80, 'Schwäbisch-Bayerische Schotterplatten- und Altmoränenlandschaft', 'Schwäbisch-Bayerische Schotterplatten- und Altmoränenlandschaft', '{BW,BY}'),
	(81, 'Schwäbisch-Bayerische Jungmoräne und Molassevorberge', 'Schwäbisch-Bayerische Jungmoräne und Molassevorberge', '{BW,BY}'),
	(82, 'Bayerische Alpen', 'Bayerische Alpen', '{BW,BY}'),
	(99, 'alle Wuchsgebiete', 'alle Wuchsgebiete', '{SH,HH,NI,HB,NW,HE,RP,BW,BY,SL,BE,BB,MV,SN,ST,TH}');

