SET search_path TO private_ci2027_001;

GRANT USAGE ON SCHEMA private_ci2027_001 TO web_anon;
GRANT web_anon TO web_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA private_ci2027_001 GRANT SELECT ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA private_ci2027_001 GRANT EXECUTE ON FUNCTIONS FROM web_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA private_ci2027_001 GRANT USAGE ON SEQUENCES TO web_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA private_ci2027_001 GRANT USAGE ON TYPES TO web_user;


--GRANT SELECT ON TABLE cluster TO web_user;
--GRANT SELECT ON TABLE plot TO web_user;
--GRANT SELECT ON TABLE wzp_tree TO web_user;
--GRANT SELECT ON TABLE plot_location TO web_user;
--GRANT SELECT ON TABLE position TO web_user;
--GRANT SELECT ON TABLE edges TO web_user;
--GRANT SELECT ON TABLE sapling_1m TO web_user;
--GRANT SELECT ON TABLE sapling_2m TO web_user;