name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

    
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          debug: true
          bump_each_commit: true
      - uses: ChanTsune/release-with-commit@v2.8.0
        with:
          regexp: "Release ((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$5"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # This token is provided by Actions, you do not need to create your own token
